syntax = "proto3";
package energychain.policy.v1;

import "gogoproto/gogo.proto";

import "energychain/policy/v1/types.proto";

option go_package = "energychain/x/policy/types";

message GenesisState {
  Params params = 1 [(gogoproto.nullable) = false];

  repeated Policy policies = 2 [(gogoproto.nullable) = false];
  repeated PolicyBinding bindings = 3 [(gogoproto.nullable) = false];
  repeated EvaluationLog evaluation_logs = 4 [(gogoproto.nullable) = false];
  uint64 evaluation_log_counter = 5;
}
