syntax = "proto3";
package energychain.eac.v1;

import "gogoproto/gogo.proto";
import "energychain/eac/v1/types.proto";

option go_package = "energychain/x/eac/types";

message Balance {
  uint64 certificate_id = 1;
  string account = 2;
  uint64 amount = 3;
}

message GenesisState {
  Params params = 1 [(gogoproto.nullable) = false];
  repeated Issuer issuers = 2 [(gogoproto.nullable) = false];
  repeated Certificate certificates = 3 [(gogoproto.nullable) = false];
  repeated Balance balances = 4 [(gogoproto.nullable) = false];
  repeated Retirement retirements = 5 [(gogoproto.nullable) = false];
  repeated BridgeAttestation bridges = 6 [(gogoproto.nullable) = false];
  uint64 certificate_id_seq = 7;
  uint64 retirement_id_seq = 8;
}
