syntax = "proto3";
package energychain.stableusd.v1;

import "cosmos/base/query/v1beta1/pagination.proto";
import "gogoproto/gogo.proto";

import "energychain/stableusd/v1/types.proto";

option go_package = "energychain/x/stableusd/types";

service Query {
  rpc Params(QueryParamsRequest) returns (QueryParamsResponse);

  rpc Denom(QueryDenomRequest) returns (QueryDenomResponse);
  rpc Denoms(QueryDenomsRequest) returns (QueryDenomsResponse);

  rpc Balance(QueryBalanceRequest) returns (QueryBalanceResponse);
  rpc Supply(QuerySupplyRequest) returns (QuerySupplyResponse);
  rpc Allowance(QueryAllowanceRequest) returns (QueryAllowanceResponse);
  rpc Flags(QueryFlagsRequest) returns (QueryFlagsResponse);

  rpc Redemption(QueryRedemptionRequest) returns (QueryRedemptionResponse);
  rpc RedemptionsByHolder(QueryRedemptionsByHolderRequest) returns (QueryRedemptionsByHolderResponse);
}

message QueryParamsRequest {}
message QueryParamsResponse { Params params = 1 [(gogoproto.nullable) = false]; }

message QueryDenomRequest { string id = 1; }
message QueryDenomResponse { StableDenom denom = 1 [(gogoproto.nullable) = false]; }

message QueryDenomsRequest { cosmos.base.query.v1beta1.PageRequest pagination = 1; }
message QueryDenomsResponse {
  repeated StableDenom denoms = 1 [(gogoproto.nullable) = false];
  cosmos.base.query.v1beta1.PageResponse pagination = 2;
}

message QueryBalanceRequest {
  string denom_id = 1;
  string account = 2;
}
message QueryBalanceResponse { uint64 amount = 1; }

message QuerySupplyRequest { string denom_id = 1; }
message QuerySupplyResponse { uint64 amount = 1; }

message QueryAllowanceRequest {
  string denom_id = 1;
  string owner = 2;
  string spender = 3;
}
message QueryAllowanceResponse { uint64 amount = 1; }

message QueryFlagsRequest {
  string denom_id = 1;
  string account = 2;
}
message QueryFlagsResponse { AccountFlags flags = 1 [(gogoproto.nullable) = false]; }

message QueryRedemptionRequest { uint64 id = 1; }
message QueryRedemptionResponse { Redemption redemption = 1 [(gogoproto.nullable) = false]; }

message QueryRedemptionsByHolderRequest {
  string holder = 1;
  cosmos.base.query.v1beta1.PageRequest pagination = 2;
}
message QueryRedemptionsByHolderResponse {
  repeated Redemption redemptions = 1 [(gogoproto.nullable) = false];
  cosmos.base.query.v1beta1.PageResponse pagination = 2;
}
