// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: energychain/eac/v1/types.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// CertificateKind enumerates the supported global EAC standards. NATIVE
// is the on-chain greenfield kind for projects that don't have an
// upstream registry (typically self-attested or DAO-governed).
type CertificateKind int32

const (
	CertificateKind_CERTIFICATE_KIND_UNSPECIFIED CertificateKind = 0
	CertificateKind_CERTIFICATE_KIND_IREC        CertificateKind = 1
	CertificateKind_CERTIFICATE_KIND_EU_GO       CertificateKind = 2
	CertificateKind_CERTIFICATE_KIND_US_REC      CertificateKind = 3
	CertificateKind_CERTIFICATE_KIND_CN_GEC      CertificateKind = 4
	CertificateKind_CERTIFICATE_KIND_AU_LGC      CertificateKind = 5
	CertificateKind_CERTIFICATE_KIND_JP_J_CREDIT CertificateKind = 6
	CertificateKind_CERTIFICATE_KIND_NATIVE      CertificateKind = 7
)

var CertificateKind_name = map[int32]string{
	0: "CERTIFICATE_KIND_UNSPECIFIED",
	1: "CERTIFICATE_KIND_IREC",
	2: "CERTIFICATE_KIND_EU_GO",
	3: "CERTIFICATE_KIND_US_REC",
	4: "CERTIFICATE_KIND_CN_GEC",
	5: "CERTIFICATE_KIND_AU_LGC",
	6: "CERTIFICATE_KIND_JP_J_CREDIT",
	7: "CERTIFICATE_KIND_NATIVE",
}

var CertificateKind_value = map[string]int32{
	"CERTIFICATE_KIND_UNSPECIFIED": 0,
	"CERTIFICATE_KIND_IREC":        1,
	"CERTIFICATE_KIND_EU_GO":       2,
	"CERTIFICATE_KIND_US_REC":      3,
	"CERTIFICATE_KIND_CN_GEC":      4,
	"CERTIFICATE_KIND_AU_LGC":      5,
	"CERTIFICATE_KIND_JP_J_CREDIT": 6,
	"CERTIFICATE_KIND_NATIVE":      7,
}

func (x CertificateKind) String() string {
	return proto.EnumName(CertificateKind_name, int32(x))
}

func (CertificateKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1b480fb2c18203bb, []int{0}
}

// Technology distinguishes the generation source. Aligned with the
// EnergyTag granular-cert spec so 24/7 CFE matching can filter on it.
type Technology int32

const (
	Technology_TECHNOLOGY_UNSPECIFIED Technology = 0
	Technology_TECHNOLOGY_SOLAR       Technology = 1
	Technology_TECHNOLOGY_WIND        Technology = 2
	Technology_TECHNOLOGY_HYDRO       Technology = 3
	Technology_TECHNOLOGY_NUCLEAR     Technology = 4
	Technology_TECHNOLOGY_BIOMASS     Technology = 5
	Technology_TECHNOLOGY_GEOTHERMAL  Technology = 6
	Technology_TECHNOLOGY_STORAGE     Technology = 7
	Technology_TECHNOLOGY_OTHER       Technology = 8
)

var Technology_name = map[int32]string{
	0: "TECHNOLOGY_UNSPECIFIED",
	1: "TECHNOLOGY_SOLAR",
	2: "TECHNOLOGY_WIND",
	3: "TECHNOLOGY_HYDRO",
	4: "TECHNOLOGY_NUCLEAR",
	5: "TECHNOLOGY_BIOMASS",
	6: "TECHNOLOGY_GEOTHERMAL",
	7: "TECHNOLOGY_STORAGE",
	8: "TECHNOLOGY_OTHER",
}

var Technology_value = map[string]int32{
	"TECHNOLOGY_UNSPECIFIED": 0,
	"TECHNOLOGY_SOLAR":       1,
	"TECHNOLOGY_WIND":        2,
	"TECHNOLOGY_HYDRO":       3,
	"TECHNOLOGY_NUCLEAR":     4,
	"TECHNOLOGY_BIOMASS":     5,
	"TECHNOLOGY_GEOTHERMAL":  6,
	"TECHNOLOGY_STORAGE":     7,
	"TECHNOLOGY_OTHER":       8,
}

func (x Technology) String() string {
	return proto.EnumName(Technology_name, int32(x))
}

func (Technology) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1b480fb2c18203bb, []int{1}
}

// IssuerStatus governs the EAC issuance authority lifecycle.
type IssuerStatus int32

const (
	IssuerStatus_ISSUER_STATUS_UNSPECIFIED IssuerStatus = 0
	IssuerStatus_ISSUER_STATUS_ACTIVE      IssuerStatus = 1
	IssuerStatus_ISSUER_STATUS_SUSPENDED   IssuerStatus = 2
	IssuerStatus_ISSUER_STATUS_REVOKED     IssuerStatus = 3
)

var IssuerStatus_name = map[int32]string{
	0: "ISSUER_STATUS_UNSPECIFIED",
	1: "ISSUER_STATUS_ACTIVE",
	2: "ISSUER_STATUS_SUSPENDED",
	3: "ISSUER_STATUS_REVOKED",
}

var IssuerStatus_value = map[string]int32{
	"ISSUER_STATUS_UNSPECIFIED": 0,
	"ISSUER_STATUS_ACTIVE":      1,
	"ISSUER_STATUS_SUSPENDED":   2,
	"ISSUER_STATUS_REVOKED":     3,
}

func (x IssuerStatus) String() string {
	return proto.EnumName(IssuerStatus_name, int32(x))
}

func (IssuerStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1b480fb2c18203bb, []int{2}
}

// CertificateStatus reflects the lifecycle of the batch as a whole.
//
//	ACTIVE       — units may transfer / retire / bridge-burn
//	SEALED       — issuer froze the batch (e.g. dispute); transfers
//	               refused but retirements still allowed so holders
//	               can liquidate compliance positions safely
//	FULLY_RETIRED — every issued unit has been retired; preserved for
//	               audit but transfers / further retires return zero.
type CertificateStatus int32

const (
	CertificateStatus_CERTIFICATE_STATUS_UNSPECIFIED   CertificateStatus = 0
	CertificateStatus_CERTIFICATE_STATUS_ACTIVE        CertificateStatus = 1
	CertificateStatus_CERTIFICATE_STATUS_SEALED        CertificateStatus = 2
	CertificateStatus_CERTIFICATE_STATUS_FULLY_RETIRED CertificateStatus = 3
)

var CertificateStatus_name = map[int32]string{
	0: "CERTIFICATE_STATUS_UNSPECIFIED",
	1: "CERTIFICATE_STATUS_ACTIVE",
	2: "CERTIFICATE_STATUS_SEALED",
	3: "CERTIFICATE_STATUS_FULLY_RETIRED",
}

var CertificateStatus_value = map[string]int32{
	"CERTIFICATE_STATUS_UNSPECIFIED":   0,
	"CERTIFICATE_STATUS_ACTIVE":        1,
	"CERTIFICATE_STATUS_SEALED":        2,
	"CERTIFICATE_STATUS_FULLY_RETIRED": 3,
}

func (x CertificateStatus) String() string {
	return proto.EnumName(CertificateStatus_name, int32(x))
}

func (CertificateStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1b480fb2c18203bb, []int{3}
}

// Issuer is a registered authority allowed to mint EAC batches.
//
// Issuers are not coextensive with mint authorities the way x/stablecoin
// models them: every EAC issuer is a standards body / certificate
// program operator (e.g. I-REC operator, EU-GO Issuing Body), so the
// authority list is short and the role is high-trust. Multi-sig keying
// is delegated to the upstream `x/auth` multisig account wrapping the
// authority address.
type Issuer struct {
	Id          string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Did         string       `protobuf:"bytes,2,opt,name=did,proto3" json:"did,omitempty"`
	DisplayName string       `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Status      IssuerStatus `protobuf:"varint,4,opt,name=status,proto3,enum=energychain.eac.v1.IssuerStatus" json:"status,omitempty"`
	// kinds is the whitelist of CertificateKind enums (as int32) the
	// issuer is permitted to mint under. Empty = all kinds.
	Kinds []int32 `protobuf:"varint,5,rep,packed,name=kinds,proto3" json:"kinds,omitempty"`
	// authority is the bech32 that must sign IssueBatch / BridgeMint.
	Authority string `protobuf:"bytes,6,opt,name=authority,proto3" json:"authority,omitempty"`
	// admin is the bech32 that may seal / unseal certificates and
	// run force-retire on its kinds.
	Admin     string `protobuf:"bytes,7,opt,name=admin,proto3" json:"admin,omitempty"`
	CreatedBy string `protobuf:"bytes,8,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt int64  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt int64  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (m *Issuer) Reset()         { *m = Issuer{} }
func (m *Issuer) String() string { return proto.CompactTextString(m) }
func (*Issuer) ProtoMessage()    {}
func (*Issuer) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b480fb2c18203bb, []int{0}
}
func (m *Issuer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Issuer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Issuer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Issuer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Issuer.Merge(m, src)
}
func (m *Issuer) XXX_Size() int {
	return m.Size()
}
func (m *Issuer) XXX_DiscardUnknown() {
	xxx_messageInfo_Issuer.DiscardUnknown(m)
}

var xxx_messageInfo_Issuer proto.InternalMessageInfo

func (m *Issuer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Issuer) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

func (m *Issuer) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Issuer) GetStatus() IssuerStatus {
	if m != nil {
		return m.Status
	}
	return IssuerStatus_ISSUER_STATUS_UNSPECIFIED
}

func (m *Issuer) GetKinds() []int32 {
	if m != nil {
		return m.Kinds
	}
	return nil
}

func (m *Issuer) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *Issuer) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

func (m *Issuer) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Issuer) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Issuer) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

// Certificate is the canonical batch record. One certificate represents
// up to `issued_units` MWh produced under the same project + device
// + grid_zone + hour window + technology, in the style of ERC-1155.
//
// retired_units only ever grows; it never exceeds issued_units.
type Certificate struct {
	Id         uint64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IssuerId   string          `protobuf:"bytes,2,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	Kind       CertificateKind `protobuf:"varint,3,opt,name=kind,proto3,enum=energychain.eac.v1.CertificateKind" json:"kind,omitempty"`
	Technology Technology      `protobuf:"varint,4,opt,name=technology,proto3,enum=energychain.eac.v1.Technology" json:"technology,omitempty"`
	ProjectId  string          `protobuf:"bytes,5,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	DeviceId   string          `protobuf:"bytes,6,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	GridZone   string          `protobuf:"bytes,7,opt,name=grid_zone,json=gridZone,proto3" json:"grid_zone,omitempty"`
	// hour_start / hour_end define the production window in unix
	// seconds. The keeper enforces hour_end > hour_start and the
	// window length must match Params.HourWindowSeconds (default 3600)
	// so 24/7 CFE matching can rely on a uniform grid.
	HourStart      int64             `protobuf:"varint,8,opt,name=hour_start,json=hourStart,proto3" json:"hour_start,omitempty"`
	HourEnd        int64             `protobuf:"varint,9,opt,name=hour_end,json=hourEnd,proto3" json:"hour_end,omitempty"`
	VintageYear    uint32            `protobuf:"varint,10,opt,name=vintage_year,json=vintageYear,proto3" json:"vintage_year,omitempty"`
	SourceRegistry string            `protobuf:"bytes,11,opt,name=source_registry,json=sourceRegistry,proto3" json:"source_registry,omitempty"`
	SourceSerial   string            `protobuf:"bytes,12,opt,name=source_serial,json=sourceSerial,proto3" json:"source_serial,omitempty"`
	IssuedUnits    uint64            `protobuf:"varint,13,opt,name=issued_units,json=issuedUnits,proto3" json:"issued_units,omitempty"`
	RetiredUnits   uint64            `protobuf:"varint,14,opt,name=retired_units,json=retiredUnits,proto3" json:"retired_units,omitempty"`
	Status         CertificateStatus `protobuf:"varint,15,opt,name=status,proto3,enum=energychain.eac.v1.CertificateStatus" json:"status,omitempty"`
	// policy_id is informational metadata for clients. The authoritative
	// binding for the transfer DSL is in x/policy keyed by
	// (asset_class="eac", asset_id=<certificate_id>).
	PolicyId  string `protobuf:"bytes,16,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	CreatedBy string `protobuf:"bytes,17,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt int64  `protobuf:"varint,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt int64  `protobuf:"varint,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (m *Certificate) Reset()         { *m = Certificate{} }
func (m *Certificate) String() string { return proto.CompactTextString(m) }
func (*Certificate) ProtoMessage()    {}
func (*Certificate) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b480fb2c18203bb, []int{1}
}
func (m *Certificate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Certificate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Certificate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Certificate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Certificate.Merge(m, src)
}
func (m *Certificate) XXX_Size() int {
	return m.Size()
}
func (m *Certificate) XXX_DiscardUnknown() {
	xxx_messageInfo_Certificate.DiscardUnknown(m)
}

var xxx_messageInfo_Certificate proto.InternalMessageInfo

func (m *Certificate) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Certificate) GetIssuerId() string {
	if m != nil {
		return m.IssuerId
	}
	return ""
}

func (m *Certificate) GetKind() CertificateKind {
	if m != nil {
		return m.Kind
	}
	return CertificateKind_CERTIFICATE_KIND_UNSPECIFIED
}

func (m *Certificate) GetTechnology() Technology {
	if m != nil {
		return m.Technology
	}
	return Technology_TECHNOLOGY_UNSPECIFIED
}

func (m *Certificate) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *Certificate) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *Certificate) GetGridZone() string {
	if m != nil {
		return m.GridZone
	}
	return ""
}

func (m *Certificate) GetHourStart() int64 {
	if m != nil {
		return m.HourStart
	}
	return 0
}

func (m *Certificate) GetHourEnd() int64 {
	if m != nil {
		return m.HourEnd
	}
	return 0
}

func (m *Certificate) GetVintageYear() uint32 {
	if m != nil {
		return m.VintageYear
	}
	return 0
}

func (m *Certificate) GetSourceRegistry() string {
	if m != nil {
		return m.SourceRegistry
	}
	return ""
}

func (m *Certificate) GetSourceSerial() string {
	if m != nil {
		return m.SourceSerial
	}
	return ""
}

func (m *Certificate) GetIssuedUnits() uint64 {
	if m != nil {
		return m.IssuedUnits
	}
	return 0
}

func (m *Certificate) GetRetiredUnits() uint64 {
	if m != nil {
		return m.RetiredUnits
	}
	return 0
}

func (m *Certificate) GetStatus() CertificateStatus {
	if m != nil {
		return m.Status
	}
	return CertificateStatus_CERTIFICATE_STATUS_UNSPECIFIED
}

func (m *Certificate) GetPolicyId() string {
	if m != nil {
		return m.PolicyId
	}
	return ""
}

func (m *Certificate) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Certificate) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Certificate) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

// Retirement is the immutable proof of one retire op. Append-only.
type Retirement struct {
	Id            uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CertificateId uint64 `protobuf:"varint,2,opt,name=certificate_id,json=certificateId,proto3" json:"certificate_id,omitempty"`
	Retirer       string `protobuf:"bytes,3,opt,name=retirer,proto3" json:"retirer,omitempty"`
	Beneficiary   string `protobuf:"bytes,4,opt,name=beneficiary,proto3" json:"beneficiary,omitempty"`
	Amount        uint64 `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Purpose       string `protobuf:"bytes,6,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Memo          string `protobuf:"bytes,7,opt,name=memo,proto3" json:"memo,omitempty"`
	RetiredAt     int64  `protobuf:"varint,8,opt,name=retired_at,json=retiredAt,proto3" json:"retired_at,omitempty"`
	Height        int64  `protobuf:"varint,9,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *Retirement) Reset()         { *m = Retirement{} }
func (m *Retirement) String() string { return proto.CompactTextString(m) }
func (*Retirement) ProtoMessage()    {}
func (*Retirement) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b480fb2c18203bb, []int{2}
}
func (m *Retirement) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Retirement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Retirement.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Retirement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Retirement.Merge(m, src)
}
func (m *Retirement) XXX_Size() int {
	return m.Size()
}
func (m *Retirement) XXX_DiscardUnknown() {
	xxx_messageInfo_Retirement.DiscardUnknown(m)
}

var xxx_messageInfo_Retirement proto.InternalMessageInfo

func (m *Retirement) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Retirement) GetCertificateId() uint64 {
	if m != nil {
		return m.CertificateId
	}
	return 0
}

func (m *Retirement) GetRetirer() string {
	if m != nil {
		return m.Retirer
	}
	return ""
}

func (m *Retirement) GetBeneficiary() string {
	if m != nil {
		return m.Beneficiary
	}
	return ""
}

func (m *Retirement) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Retirement) GetPurpose() string {
	if m != nil {
		return m.Purpose
	}
	return ""
}

func (m *Retirement) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *Retirement) GetRetiredAt() int64 {
	if m != nil {
		return m.RetiredAt
	}
	return 0
}

func (m *Retirement) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

// BridgeAttestation pins a certificate to its mirror in an upstream
// registry. The keeper consults the bound oracle topic on
// BridgeMint / BridgeBurn to enforce the on-chain mirror MUST not
// exceed the off-chain locked count.
type BridgeAttestation struct {
	CertificateId  uint64 `protobuf:"varint,1,opt,name=certificate_id,json=certificateId,proto3" json:"certificate_id,omitempty"`
	SourceRegistry string `protobuf:"bytes,2,opt,name=source_registry,json=sourceRegistry,proto3" json:"source_registry,omitempty"`
	SourceSerial   string `protobuf:"bytes,3,opt,name=source_serial,json=sourceSerial,proto3" json:"source_serial,omitempty"`
	// oracle_topic_id holds the oracle topic that aggregates the
	// upstream "locked units" attestations from bridge oracles.
	OracleTopicId string `protobuf:"bytes,4,opt,name=oracle_topic_id,json=oracleTopicId,proto3" json:"oracle_topic_id,omitempty"`
	// max_staleness_seconds bounds the freshness of the latest
	// aggregation; mints/burns fail closed beyond this age.
	MaxStalenessSeconds uint32 `protobuf:"varint,5,opt,name=max_staleness_seconds,json=maxStalenessSeconds,proto3" json:"max_staleness_seconds,omitempty"`
	UpdatedAt           int64  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (m *BridgeAttestation) Reset()         { *m = BridgeAttestation{} }
func (m *BridgeAttestation) String() string { return proto.CompactTextString(m) }
func (*BridgeAttestation) ProtoMessage()    {}
func (*BridgeAttestation) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b480fb2c18203bb, []int{3}
}
func (m *BridgeAttestation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BridgeAttestation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BridgeAttestation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BridgeAttestation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BridgeAttestation.Merge(m, src)
}
func (m *BridgeAttestation) XXX_Size() int {
	return m.Size()
}
func (m *BridgeAttestation) XXX_DiscardUnknown() {
	xxx_messageInfo_BridgeAttestation.DiscardUnknown(m)
}

var xxx_messageInfo_BridgeAttestation proto.InternalMessageInfo

func (m *BridgeAttestation) GetCertificateId() uint64 {
	if m != nil {
		return m.CertificateId
	}
	return 0
}

func (m *BridgeAttestation) GetSourceRegistry() string {
	if m != nil {
		return m.SourceRegistry
	}
	return ""
}

func (m *BridgeAttestation) GetSourceSerial() string {
	if m != nil {
		return m.SourceSerial
	}
	return ""
}

func (m *BridgeAttestation) GetOracleTopicId() string {
	if m != nil {
		return m.OracleTopicId
	}
	return ""
}

func (m *BridgeAttestation) GetMaxStalenessSeconds() uint32 {
	if m != nil {
		return m.MaxStalenessSeconds
	}
	return 0
}

func (m *BridgeAttestation) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

// Params bound the variable-length state collections.
type Params struct {
	MaxIssuers        uint32 `protobuf:"varint,1,opt,name=max_issuers,json=maxIssuers,proto3" json:"max_issuers,omitempty"`
	MaxKindsPerIssuer uint32 `protobuf:"varint,2,opt,name=max_kinds_per_issuer,json=maxKindsPerIssuer,proto3" json:"max_kinds_per_issuer,omitempty"`
	MaxUnitsPerBatch  uint32 `protobuf:"varint,3,opt,name=max_units_per_batch,json=maxUnitsPerBatch,proto3" json:"max_units_per_batch,omitempty"`
	// hour_window_seconds enforces a uniform production-window length
	// (default 3600). Set to 0 to disable the check (e.g. test chains
	// that want sub-hour granular certs).
	HourWindowSeconds uint32 `protobuf:"varint,4,opt,name=hour_window_seconds,json=hourWindowSeconds,proto3" json:"hour_window_seconds,omitempty"`
	// require_sanctions_clear, when true, the keeper rejects any
	// transfer / retire whose counterparty appears on a sanctions list.
	// Default true (fail-closed).
	RequireSanctionsClear bool `protobuf:"varint,5,opt,name=require_sanctions_clear,json=requireSanctionsClear,proto3" json:"require_sanctions_clear,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b480fb2c18203bb, []int{4}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMaxIssuers() uint32 {
	if m != nil {
		return m.MaxIssuers
	}
	return 0
}

func (m *Params) GetMaxKindsPerIssuer() uint32 {
	if m != nil {
		return m.MaxKindsPerIssuer
	}
	return 0
}

func (m *Params) GetMaxUnitsPerBatch() uint32 {
	if m != nil {
		return m.MaxUnitsPerBatch
	}
	return 0
}

func (m *Params) GetHourWindowSeconds() uint32 {
	if m != nil {
		return m.HourWindowSeconds
	}
	return 0
}

func (m *Params) GetRequireSanctionsClear() bool {
	if m != nil {
		return m.RequireSanctionsClear
	}
	return false
}

func init() {
	proto.RegisterEnum("energychain.eac.v1.CertificateKind", CertificateKind_name, CertificateKind_value)
	proto.RegisterEnum("energychain.eac.v1.Technology", Technology_name, Technology_value)
	proto.RegisterEnum("energychain.eac.v1.IssuerStatus", IssuerStatus_name, IssuerStatus_value)
	proto.RegisterEnum("energychain.eac.v1.CertificateStatus", CertificateStatus_name, CertificateStatus_value)
	proto.RegisterType((*Issuer)(nil), "energychain.eac.v1.Issuer")
	proto.RegisterType((*Certificate)(nil), "energychain.eac.v1.Certificate")
	proto.RegisterType((*Retirement)(nil), "energychain.eac.v1.Retirement")
	proto.RegisterType((*BridgeAttestation)(nil), "energychain.eac.v1.BridgeAttestation")
	proto.RegisterType((*Params)(nil), "energychain.eac.v1.Params")
}

func init() { proto.RegisterFile("energychain/eac/v1/types.proto", fileDescriptor_1b480fb2c18203bb) }

var fileDescriptor_1b480fb2c18203bb = []byte{
	// 1251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x17, 0x35, 0xf5, 0x67, 0xe9, 0xca, 0xb2, 0xe9, 0xb1, 0x9d, 0xd0, 0xf9, 0xd1, 0xa7, 0xcf, 0x69,
	0x5a, 0xc3, 0x40, 0x6d, 0x24, 0x05, 0xda, 0x6e, 0x5a, 0x80, 0x96, 0x18, 0x87, 0x89, 0x22, 0x19,
	0x43, 0x29, 0x81, 0xb3, 0x21, 0xc6, 0xe4, 0x44, 0x9a, 0x56, 0x22, 0xd5, 0x21, 0xe5, 0x58, 0xdd,
	0xb4, 0x40, 0x5f, 0xa0, 0xfb, 0xbe, 0x43, 0xd7, 0x7d, 0x84, 0x2e, 0xb3, 0xec, 0xb2, 0x70, 0x9e,
	0xa0, 0xfb, 0x2e, 0x8a, 0x99, 0xa1, 0x14, 0x46, 0x26, 0xd2, 0xee, 0x34, 0xe7, 0xdc, 0x3b, 0x73,
	0xef, 0x99, 0x33, 0x57, 0x84, 0x3a, 0x0d, 0x28, 0x1f, 0xcc, 0xbc, 0x21, 0x61, 0xc1, 0x11, 0x25,
	0xde, 0xd1, 0xc5, 0x83, 0xa3, 0x78, 0x36, 0xa1, 0xd1, 0xe1, 0x84, 0x87, 0x71, 0x88, 0x50, 0x8a,
	0x3f, 0xa4, 0xc4, 0x3b, 0xbc, 0x78, 0x70, 0x6b, 0x7b, 0x10, 0x0e, 0x42, 0x49, 0x1f, 0x89, 0x5f,
	0x2a, 0x72, 0xef, 0xd7, 0x1c, 0x94, 0xec, 0x28, 0x9a, 0x52, 0x8e, 0xd6, 0x21, 0xc7, 0x7c, 0x43,
	0x6b, 0x68, 0xfb, 0x15, 0x9c, 0x63, 0x3e, 0xd2, 0x21, 0xef, 0x33, 0xdf, 0xc8, 0x49, 0x40, 0xfc,
	0x44, 0xff, 0x87, 0x35, 0x9f, 0x45, 0x93, 0x11, 0x99, 0xb9, 0x01, 0x19, 0x53, 0x23, 0x2f, 0xa9,
	0x6a, 0x82, 0x75, 0xc8, 0x98, 0xa2, 0x2f, 0xa1, 0x14, 0xc5, 0x24, 0x9e, 0x46, 0x46, 0xa1, 0xa1,
	0xed, 0xaf, 0x3f, 0x6c, 0x1c, 0x5e, 0x2f, 0xe5, 0x50, 0x1d, 0xe8, 0xc8, 0x38, 0x9c, 0xc4, 0xa3,
	0x6d, 0x28, 0x7e, 0xcb, 0x02, 0x3f, 0x32, 0x8a, 0x8d, 0xfc, 0x7e, 0x11, 0xab, 0x05, 0xba, 0x03,
	0x15, 0x32, 0x8d, 0x87, 0x21, 0x67, 0xf1, 0xcc, 0x28, 0xc9, 0xf3, 0xde, 0x01, 0x22, 0x87, 0xf8,
	0x63, 0x16, 0x18, 0xab, 0x92, 0x51, 0x0b, 0x74, 0x17, 0xc0, 0xe3, 0x94, 0xc4, 0xd4, 0x77, 0xcf,
	0x67, 0x46, 0x59, 0x25, 0x25, 0xc8, 0xf1, 0x2c, 0x4d, 0x93, 0xd8, 0xa8, 0x34, 0xb4, 0xfd, 0xfc,
	0x82, 0x36, 0x63, 0x41, 0x4f, 0x27, 0xfe, 0x9c, 0x06, 0x45, 0x27, 0x88, 0x19, 0xef, 0xfd, 0x56,
	0x84, 0x6a, 0x93, 0xf2, 0x98, 0xbd, 0x62, 0x1e, 0x89, 0x69, 0x4a, 0xb5, 0x82, 0x54, 0xed, 0x36,
	0x54, 0x98, 0x6c, 0xcf, 0x5d, 0x68, 0x57, 0x56, 0x80, 0xed, 0xa3, 0x2f, 0xa0, 0x20, 0xda, 0x92,
	0xc2, 0xad, 0x3f, 0xbc, 0x97, 0xa5, 0x4d, 0x6a, 0xef, 0xa7, 0x2c, 0xf0, 0xb1, 0x4c, 0x40, 0x5f,
	0x03, 0xc4, 0xd4, 0x1b, 0x06, 0xe1, 0x28, 0x1c, 0xcc, 0x12, 0x69, 0xeb, 0x59, 0xe9, 0xbd, 0x45,
	0x14, 0x4e, 0x65, 0x88, 0xa6, 0x26, 0x3c, 0xfc, 0x86, 0x7a, 0xb1, 0x28, 0xab, 0xa8, 0x24, 0x49,
	0x10, 0x5b, 0x16, 0xed, 0xd3, 0x0b, 0xe6, 0x51, 0xc1, 0x2a, 0x95, 0xcb, 0x0a, 0x50, 0xe4, 0x80,
	0x33, 0xdf, 0xfd, 0x3e, 0x0c, 0x68, 0x22, 0x74, 0x59, 0x00, 0x2f, 0xc3, 0x80, 0x8a, 0x8d, 0x87,
	0xe1, 0x94, 0xbb, 0x51, 0x4c, 0x78, 0x2c, 0xb5, 0xce, 0xe3, 0x8a, 0x40, 0x1c, 0x01, 0xa0, 0x5d,
	0x28, 0x4b, 0x9a, 0x06, 0x7e, 0xa2, 0xf4, 0xaa, 0x58, 0x5b, 0x81, 0x34, 0xd3, 0x05, 0x0b, 0x62,
	0x32, 0xa0, 0xee, 0x8c, 0x12, 0x2e, 0x95, 0xae, 0xe1, 0x6a, 0x82, 0x9d, 0x51, 0xc2, 0xd1, 0x27,
	0xb0, 0x11, 0x85, 0x53, 0xee, 0x51, 0x97, 0xd3, 0x01, 0x8b, 0x62, 0x3e, 0x33, 0xaa, 0xf2, 0xfc,
	0x75, 0x05, 0xe3, 0x04, 0x45, 0xf7, 0xa0, 0x96, 0x04, 0x46, 0x94, 0x33, 0x32, 0x32, 0xd6, 0x64,
	0xd8, 0x9a, 0x02, 0x1d, 0x89, 0x89, 0x03, 0xe5, 0x45, 0xf8, 0xee, 0x34, 0x60, 0x71, 0x64, 0xd4,
	0xe4, 0x9d, 0x55, 0x15, 0xd6, 0x17, 0x90, 0xd8, 0x87, 0xd3, 0x98, 0xf1, 0x45, 0xcc, 0xba, 0x8c,
	0x59, 0x4b, 0x40, 0x15, 0xf4, 0xd5, 0xc2, 0xe2, 0x1b, 0xf2, 0x1e, 0xee, 0xff, 0xcb, 0x35, 0x2e,
	0xf9, 0xfc, 0x36, 0x54, 0x26, 0xe1, 0x88, 0x79, 0x33, 0xa1, 0xb5, 0xae, 0xe4, 0x54, 0x80, 0xed,
	0x2f, 0x59, 0x77, 0xf3, 0xc3, 0xd6, 0x45, 0x1f, 0xb6, 0xee, 0xd6, 0xb2, 0x75, 0xff, 0xd6, 0x00,
	0xb0, 0xec, 0x64, 0x4c, 0x83, 0xf8, 0x9a, 0x73, 0xef, 0xc3, 0xba, 0xf7, 0xae, 0xea, 0xb9, 0x7d,
	0x0b, 0xb8, 0x96, 0x42, 0x6d, 0x1f, 0x19, 0xb0, 0xaa, 0xe4, 0xe0, 0xc9, 0xfb, 0x9f, 0x2f, 0x51,
	0x03, 0xaa, 0xe7, 0x34, 0xa0, 0xaf, 0x98, 0xc7, 0x08, 0x57, 0x2e, 0xad, 0xe0, 0x34, 0x84, 0x6e,
	0x40, 0x89, 0x8c, 0xc3, 0x69, 0x10, 0x4b, 0x0b, 0x16, 0x70, 0xb2, 0x12, 0x7b, 0x4e, 0xa6, 0x7c,
	0x12, 0x46, 0x34, 0x71, 0xdf, 0x7c, 0x89, 0x10, 0x14, 0xc6, 0x74, 0x1c, 0x26, 0xbe, 0x93, 0xbf,
	0x45, 0x9b, 0xf3, 0x5b, 0x22, 0x0b, 0xcf, 0x25, 0x88, 0x19, 0x8b, 0x43, 0x86, 0x94, 0x0d, 0x86,
	0xf3, 0xb7, 0x9d, 0xac, 0xf6, 0x7e, 0xca, 0xc1, 0xe6, 0x31, 0x67, 0xfe, 0x80, 0x9a, 0x71, 0x4c,
	0xc5, 0x6d, 0xb0, 0x30, 0xc8, 0xe8, 0x5a, 0xcb, 0xea, 0x3a, 0xc3, 0x8a, 0xb9, 0xff, 0x66, 0xc5,
	0x7c, 0x86, 0x15, 0x3f, 0x86, 0x8d, 0x90, 0x13, 0x6f, 0x44, 0xdd, 0x38, 0x9c, 0x30, 0x4f, 0x9c,
	0xaa, 0xd4, 0xaa, 0x29, 0xb8, 0x27, 0x50, 0xdb, 0x47, 0x0f, 0x61, 0x67, 0x4c, 0x2e, 0xc5, 0xe3,
	0x1a, 0xd1, 0x80, 0x46, 0x91, 0x1b, 0x51, 0x2f, 0x54, 0x33, 0x52, 0x3c, 0x96, 0xad, 0x31, 0xb9,
	0x74, 0xe6, 0x9c, 0xa3, 0xa8, 0x25, 0x13, 0x94, 0x96, 0x4d, 0xf0, 0x97, 0x06, 0xa5, 0x53, 0xc2,
	0xc9, 0x38, 0x42, 0xff, 0x83, 0xaa, 0xd8, 0x5d, 0x4d, 0xa7, 0x48, 0xf6, 0x5d, 0xc3, 0x30, 0x26,
	0x97, 0x6a, 0x3e, 0x47, 0xe8, 0x08, 0xb6, 0x45, 0x80, 0x9c, 0xc4, 0xee, 0x44, 0x8c, 0x34, 0x49,
	0xc8, 0xce, 0x6b, 0x78, 0x73, 0x4c, 0x2e, 0xc5, 0x88, 0x8a, 0x4e, 0x29, 0x4f, 0xfe, 0x42, 0x3e,
	0x05, 0x51, 0x92, 0x7a, 0x3b, 0x32, 0xe1, 0x9c, 0xc4, 0xde, 0x50, 0x4a, 0x50, 0xc3, 0xfa, 0x98,
	0x5c, 0xca, 0x17, 0x74, 0x4a, 0xf9, 0xb1, 0xc0, 0xd1, 0x21, 0x6c, 0xc9, 0xe9, 0xf0, 0x9a, 0x05,
	0x7e, 0xf8, 0x7a, 0xd1, 0x5c, 0x41, 0x6d, 0x2f, 0xa8, 0x17, 0x92, 0x99, 0xb7, 0xf6, 0x39, 0xdc,
	0xe4, 0xf4, 0xbb, 0x29, 0xe3, 0xd4, 0x8d, 0x48, 0xe0, 0x89, 0xfb, 0x8b, 0x5c, 0x6f, 0x24, 0xa6,
	0x87, 0x10, 0xa4, 0x8c, 0x77, 0x12, 0xda, 0x99, 0xb3, 0x4d, 0x41, 0x1e, 0xfc, 0x98, 0x83, 0x8d,
	0xa5, 0xb9, 0x8a, 0x1a, 0x70, 0xa7, 0x69, 0xe1, 0x9e, 0xfd, 0xc8, 0x6e, 0x9a, 0x3d, 0xcb, 0x7d,
	0x6a, 0x77, 0x5a, 0x6e, 0xbf, 0xe3, 0x9c, 0x5a, 0x4d, 0xfb, 0x91, 0x6d, 0xb5, 0xf4, 0x15, 0xb4,
	0x0b, 0x3b, 0xd7, 0x22, 0x6c, 0x6c, 0x35, 0x75, 0x0d, 0xdd, 0x82, 0x1b, 0xd7, 0x28, 0xab, 0xef,
	0x9e, 0x74, 0xf5, 0x1c, 0xba, 0x0d, 0x37, 0xaf, 0x6f, 0xec, 0xb8, 0x22, 0x31, 0x9f, 0x49, 0x36,
	0x3b, 0xee, 0x89, 0xd5, 0xd4, 0x0b, 0x99, 0xa4, 0xd9, 0x77, 0xdb, 0x27, 0x4d, 0xbd, 0x98, 0x59,
	0xef, 0x93, 0x53, 0xf7, 0x89, 0xdb, 0xc4, 0x56, 0xcb, 0xee, 0xe9, 0xa5, 0xcc, 0xf4, 0x8e, 0xd9,
	0xb3, 0x9f, 0x5b, 0xfa, 0xea, 0xc1, 0x95, 0x06, 0xf0, 0xee, 0xbf, 0x41, 0x34, 0xd0, 0xb3, 0x9a,
	0x8f, 0x3b, 0xdd, 0x76, 0xf7, 0xe4, 0x6c, 0xa9, 0xef, 0x6d, 0xd0, 0x53, 0x9c, 0xd3, 0x6d, 0x9b,
	0x58, 0xd7, 0xd0, 0x16, 0x6c, 0xa4, 0xd0, 0x17, 0x76, 0xa7, 0xa5, 0xe7, 0x96, 0x42, 0x1f, 0x9f,
	0xb5, 0x70, 0x57, 0xcf, 0xa3, 0x1b, 0x80, 0x52, 0x68, 0xa7, 0xdf, 0x6c, 0x5b, 0x26, 0xd6, 0x0b,
	0x4b, 0xf8, 0xb1, 0xdd, 0x7d, 0x66, 0x3a, 0x8e, 0x5e, 0x14, 0x42, 0xa7, 0xf0, 0x13, 0xab, 0xdb,
	0x7b, 0x6c, 0xe1, 0x67, 0x66, 0x5b, 0x2f, 0x2d, 0xa5, 0x38, 0xbd, 0x2e, 0x36, 0x4f, 0x2c, 0x7d,
	0x75, 0xe9, 0x60, 0x99, 0xa0, 0x97, 0x0f, 0x7e, 0x80, 0xb5, 0xf4, 0xa7, 0x05, 0xba, 0x0b, 0xbb,
	0xb6, 0xe3, 0xf4, 0x2d, 0xec, 0x3a, 0x3d, 0xb3, 0xd7, 0x77, 0x96, 0x1a, 0x35, 0x60, 0xfb, 0x7d,
	0xda, 0x6c, 0x4a, 0xb5, 0x34, 0x21, 0xe5, 0xfb, 0x8c, 0xd3, 0x77, 0x4e, 0xad, 0x4e, 0xcb, 0x12,
	0x4d, 0xef, 0xc2, 0xce, 0xfb, 0x24, 0xb6, 0x9e, 0x77, 0x9f, 0x5a, 0x2d, 0x3d, 0x7f, 0xf0, 0x8b,
	0x06, 0x9b, 0xd7, 0x26, 0x3f, 0xda, 0x83, 0x7a, 0xfa, 0x62, 0x32, 0x6b, 0xb9, 0x0b, 0xbb, 0x19,
	0x31, 0x8b, 0x82, 0xb2, 0x69, 0xc7, 0x32, 0xdb, 0xb2, 0xa4, 0x8f, 0xa0, 0x91, 0x41, 0x3f, 0xea,
	0xb7, 0xdb, 0x67, 0x2e, 0xb6, 0x7a, 0x36, 0x16, 0xd5, 0x1d, 0x3f, 0xf8, 0xfd, 0xaa, 0xae, 0xbd,
	0xb9, 0xaa, 0x6b, 0x7f, 0x5e, 0xd5, 0xb5, 0x9f, 0xdf, 0xd6, 0x57, 0xde, 0xbc, 0xad, 0xaf, 0xfc,
	0xf1, 0xb6, 0xbe, 0xf2, 0xf2, 0x66, 0xfa, 0x7b, 0xf2, 0x52, 0x7e, 0x51, 0xca, 0xcf, 0xc9, 0xf3,
	0x92, 0xfc, 0x4a, 0xfc, 0xec, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x22, 0x26, 0x5b, 0x71,
	0x0a, 0x00, 0x00,
}

func (m *Issuer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Issuer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Issuer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UpdatedAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.UpdatedAt))
		i--
		dAtA[i] = 0x50
	}
	if m.CreatedAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x48
	}
	if len(m.CreatedBy) > 0 {
		i -= len(m.CreatedBy)
		copy(dAtA[i:], m.CreatedBy)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.CreatedBy)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Admin) > 0 {
		i -= len(m.Admin)
		copy(dAtA[i:], m.Admin)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Admin)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Kinds) > 0 {
		dAtA2 := make([]byte, len(m.Kinds)*10)
		var j1 int
		for _, num1 := range m.Kinds {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintTypes(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x2a
	}
	if m.Status != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x20
	}
	if len(m.DisplayName) > 0 {
		i -= len(m.DisplayName)
		copy(dAtA[i:], m.DisplayName)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.DisplayName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Did) > 0 {
		i -= len(m.Did)
		copy(dAtA[i:], m.Did)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Did)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Certificate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Certificate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Certificate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UpdatedAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.UpdatedAt))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x98
	}
	if m.CreatedAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if len(m.CreatedBy) > 0 {
		i -= len(m.CreatedBy)
		copy(dAtA[i:], m.CreatedBy)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.CreatedBy)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x8a
	}
	if len(m.PolicyId) > 0 {
		i -= len(m.PolicyId)
		copy(dAtA[i:], m.PolicyId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.PolicyId)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	if m.Status != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x78
	}
	if m.RetiredUnits != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.RetiredUnits))
		i--
		dAtA[i] = 0x70
	}
	if m.IssuedUnits != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.IssuedUnits))
		i--
		dAtA[i] = 0x68
	}
	if len(m.SourceSerial) > 0 {
		i -= len(m.SourceSerial)
		copy(dAtA[i:], m.SourceSerial)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.SourceSerial)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.SourceRegistry) > 0 {
		i -= len(m.SourceRegistry)
		copy(dAtA[i:], m.SourceRegistry)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.SourceRegistry)))
		i--
		dAtA[i] = 0x5a
	}
	if m.VintageYear != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.VintageYear))
		i--
		dAtA[i] = 0x50
	}
	if m.HourEnd != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.HourEnd))
		i--
		dAtA[i] = 0x48
	}
	if m.HourStart != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.HourStart))
		i--
		dAtA[i] = 0x40
	}
	if len(m.GridZone) > 0 {
		i -= len(m.GridZone)
		copy(dAtA[i:], m.GridZone)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.GridZone)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.DeviceId) > 0 {
		i -= len(m.DeviceId)
		copy(dAtA[i:], m.DeviceId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.DeviceId)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.ProjectId) > 0 {
		i -= len(m.ProjectId)
		copy(dAtA[i:], m.ProjectId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ProjectId)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Technology != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Technology))
		i--
		dAtA[i] = 0x20
	}
	if m.Kind != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Kind))
		i--
		dAtA[i] = 0x18
	}
	if len(m.IssuerId) > 0 {
		i -= len(m.IssuerId)
		copy(dAtA[i:], m.IssuerId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.IssuerId)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Retirement) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Retirement) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Retirement) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x48
	}
	if m.RetiredAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.RetiredAt))
		i--
		dAtA[i] = 0x40
	}
	if len(m.Memo) > 0 {
		i -= len(m.Memo)
		copy(dAtA[i:], m.Memo)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Memo)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Purpose) > 0 {
		i -= len(m.Purpose)
		copy(dAtA[i:], m.Purpose)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Purpose)))
		i--
		dAtA[i] = 0x32
	}
	if m.Amount != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Beneficiary) > 0 {
		i -= len(m.Beneficiary)
		copy(dAtA[i:], m.Beneficiary)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Beneficiary)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Retirer) > 0 {
		i -= len(m.Retirer)
		copy(dAtA[i:], m.Retirer)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Retirer)))
		i--
		dAtA[i] = 0x1a
	}
	if m.CertificateId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.CertificateId))
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BridgeAttestation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BridgeAttestation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BridgeAttestation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UpdatedAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.UpdatedAt))
		i--
		dAtA[i] = 0x30
	}
	if m.MaxStalenessSeconds != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MaxStalenessSeconds))
		i--
		dAtA[i] = 0x28
	}
	if len(m.OracleTopicId) > 0 {
		i -= len(m.OracleTopicId)
		copy(dAtA[i:], m.OracleTopicId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.OracleTopicId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.SourceSerial) > 0 {
		i -= len(m.SourceSerial)
		copy(dAtA[i:], m.SourceSerial)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.SourceSerial)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SourceRegistry) > 0 {
		i -= len(m.SourceRegistry)
		copy(dAtA[i:], m.SourceRegistry)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.SourceRegistry)))
		i--
		dAtA[i] = 0x12
	}
	if m.CertificateId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.CertificateId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RequireSanctionsClear {
		i--
		if m.RequireSanctionsClear {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.HourWindowSeconds != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.HourWindowSeconds))
		i--
		dAtA[i] = 0x20
	}
	if m.MaxUnitsPerBatch != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MaxUnitsPerBatch))
		i--
		dAtA[i] = 0x18
	}
	if m.MaxKindsPerIssuer != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MaxKindsPerIssuer))
		i--
		dAtA[i] = 0x10
	}
	if m.MaxIssuers != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MaxIssuers))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Issuer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Did)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.DisplayName)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovTypes(uint64(m.Status))
	}
	if len(m.Kinds) > 0 {
		l = 0
		for _, e := range m.Kinds {
			l += sovTypes(uint64(e))
		}
		n += 1 + sovTypes(uint64(l)) + l
	}
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Admin)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.CreatedBy)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovTypes(uint64(m.CreatedAt))
	}
	if m.UpdatedAt != 0 {
		n += 1 + sovTypes(uint64(m.UpdatedAt))
	}
	return n
}

func (m *Certificate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTypes(uint64(m.Id))
	}
	l = len(m.IssuerId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Kind != 0 {
		n += 1 + sovTypes(uint64(m.Kind))
	}
	if m.Technology != 0 {
		n += 1 + sovTypes(uint64(m.Technology))
	}
	l = len(m.ProjectId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.DeviceId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.GridZone)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.HourStart != 0 {
		n += 1 + sovTypes(uint64(m.HourStart))
	}
	if m.HourEnd != 0 {
		n += 1 + sovTypes(uint64(m.HourEnd))
	}
	if m.VintageYear != 0 {
		n += 1 + sovTypes(uint64(m.VintageYear))
	}
	l = len(m.SourceRegistry)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.SourceSerial)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.IssuedUnits != 0 {
		n += 1 + sovTypes(uint64(m.IssuedUnits))
	}
	if m.RetiredUnits != 0 {
		n += 1 + sovTypes(uint64(m.RetiredUnits))
	}
	if m.Status != 0 {
		n += 1 + sovTypes(uint64(m.Status))
	}
	l = len(m.PolicyId)
	if l > 0 {
		n += 2 + l + sovTypes(uint64(l))
	}
	l = len(m.CreatedBy)
	if l > 0 {
		n += 2 + l + sovTypes(uint64(l))
	}
	if m.CreatedAt != 0 {
		n += 2 + sovTypes(uint64(m.CreatedAt))
	}
	if m.UpdatedAt != 0 {
		n += 2 + sovTypes(uint64(m.UpdatedAt))
	}
	return n
}

func (m *Retirement) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTypes(uint64(m.Id))
	}
	if m.CertificateId != 0 {
		n += 1 + sovTypes(uint64(m.CertificateId))
	}
	l = len(m.Retirer)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Beneficiary)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovTypes(uint64(m.Amount))
	}
	l = len(m.Purpose)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Memo)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.RetiredAt != 0 {
		n += 1 + sovTypes(uint64(m.RetiredAt))
	}
	if m.Height != 0 {
		n += 1 + sovTypes(uint64(m.Height))
	}
	return n
}

func (m *BridgeAttestation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CertificateId != 0 {
		n += 1 + sovTypes(uint64(m.CertificateId))
	}
	l = len(m.SourceRegistry)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.SourceSerial)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.OracleTopicId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.MaxStalenessSeconds != 0 {
		n += 1 + sovTypes(uint64(m.MaxStalenessSeconds))
	}
	if m.UpdatedAt != 0 {
		n += 1 + sovTypes(uint64(m.UpdatedAt))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxIssuers != 0 {
		n += 1 + sovTypes(uint64(m.MaxIssuers))
	}
	if m.MaxKindsPerIssuer != 0 {
		n += 1 + sovTypes(uint64(m.MaxKindsPerIssuer))
	}
	if m.MaxUnitsPerBatch != 0 {
		n += 1 + sovTypes(uint64(m.MaxUnitsPerBatch))
	}
	if m.HourWindowSeconds != 0 {
		n += 1 + sovTypes(uint64(m.HourWindowSeconds))
	}
	if m.RequireSanctionsClear {
		n += 2
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Issuer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Issuer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Issuer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Did = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisplayName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DisplayName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= IssuerStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType == 0 {
				var v int32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTypes
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Kinds = append(m.Kinds, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTypes
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTypes
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthTypes
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Kinds) == 0 {
					m.Kinds = make([]int32, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTypes
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= int32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Kinds = append(m.Kinds, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Kinds", wireType)
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			m.UpdatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Certificate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Certificate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Certificate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IssuerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kind", wireType)
			}
			m.Kind = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Kind |= CertificateKind(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Technology", wireType)
			}
			m.Technology = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Technology |= Technology(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProjectId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeviceId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GridZone", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GridZone = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HourStart", wireType)
			}
			m.HourStart = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HourStart |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HourEnd", wireType)
			}
			m.HourEnd = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HourEnd |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VintageYear", wireType)
			}
			m.VintageYear = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VintageYear |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceRegistry", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceRegistry = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceSerial", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceSerial = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuedUnits", wireType)
			}
			m.IssuedUnits = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IssuedUnits |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RetiredUnits", wireType)
			}
			m.RetiredUnits = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RetiredUnits |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= CertificateStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PolicyId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 19:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			m.UpdatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Retirement) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Retirement: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Retirement: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CertificateId", wireType)
			}
			m.CertificateId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CertificateId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Retirer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Retirer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Beneficiary", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Beneficiary = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Purpose", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Purpose = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Memo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RetiredAt", wireType)
			}
			m.RetiredAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RetiredAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BridgeAttestation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BridgeAttestation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BridgeAttestation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CertificateId", wireType)
			}
			m.CertificateId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CertificateId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceRegistry", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceRegistry = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceSerial", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceSerial = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleTopicId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OracleTopicId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxStalenessSeconds", wireType)
			}
			m.MaxStalenessSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxStalenessSeconds |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			m.UpdatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxIssuers", wireType)
			}
			m.MaxIssuers = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxIssuers |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxKindsPerIssuer", wireType)
			}
			m.MaxKindsPerIssuer = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxKindsPerIssuer |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxUnitsPerBatch", wireType)
			}
			m.MaxUnitsPerBatch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxUnitsPerBatch |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HourWindowSeconds", wireType)
			}
			m.HourWindowSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HourWindowSeconds |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequireSanctionsClear", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RequireSanctionsClear = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
