syntax = "proto3";
package energychain.rwa.v1;

import "gogoproto/gogo.proto";
import "energychain/rwa/v1/types.proto";

option go_package = "energychain/x/rwa/types";

message Balance {
  uint64 token_id = 1;
  string account = 2;
  uint64 amount = 3;
}

message PendingRedemptionUnits {
  uint64 token_id = 1;
  uint64 amount = 2; // sum of all PENDING request amounts for this token
}

message GenesisState {
  Params params = 1 [(gogoproto.nullable) = false];
  repeated Issuer issuers = 2 [(gogoproto.nullable) = false];
  repeated Token tokens = 3 [(gogoproto.nullable) = false];
  repeated Balance balances = 4 [(gogoproto.nullable) = false];
  repeated AccountFlags account_flags = 5 [(gogoproto.nullable) = false];
  repeated FrozenBalance frozen = 6 [(gogoproto.nullable) = false];
  repeated Lockup lockups = 7 [(gogoproto.nullable) = false];
  repeated SnapshotMeta snapshots = 8 [(gogoproto.nullable) = false];
  repeated SnapshotBalance snapshot_balances = 9 [(gogoproto.nullable) = false];
  repeated Distribution distributions = 10 [(gogoproto.nullable) = false];
  repeated DistributionClaim distribution_claims = 11 [(gogoproto.nullable) = false];
  repeated RedemptionRequest redemptions = 12 [(gogoproto.nullable) = false];
  repeated PendingRedemptionUnits pending_redemption_units = 13 [(gogoproto.nullable) = false];
  uint64 token_id_seq = 14;
  uint64 lockup_id_seq = 15;
  uint64 snapshot_id_seq = 16;
  uint64 distribution_id_seq = 17;
  uint64 redemption_id_seq = 18;
}
