syntax = "proto3";
package energychain.sanctions.v1;

import "gogoproto/gogo.proto";

import "energychain/sanctions/v1/types.proto";

option go_package = "energychain/x/sanctions/types";

message GenesisState {
  Params params = 1 [(gogoproto.nullable) = false];

  repeated SanctionList lists = 2 [(gogoproto.nullable) = false];
  repeated SanctionEntry entries = 3 [(gogoproto.nullable) = false];
  repeated Proposal proposals = 4 [(gogoproto.nullable) = false];
  repeated SanctionHit hits = 5 [(gogoproto.nullable) = false];

  uint64 proposal_counter = 6;
  uint64 hit_counter = 7;
}
