syntax = "proto3";
package energychain.did.v1;

import "gogoproto/gogo.proto";
import "cosmos/base/query/v1beta1/pagination.proto";
import "energychain/did/v1/types.proto";

option go_package = "energychain/x/did/types";

service Query {
  rpc DID                (QueryDIDRequest)                returns (QueryDIDResponse);
  rpc AllDIDs            (QueryAllDIDsRequest)            returns (QueryAllDIDsResponse);
  rpc Credential         (QueryCredentialRequest)         returns (QueryCredentialResponse);
  rpc CredentialsBySubject (QueryCredentialsBySubjectRequest) returns (QueryCredentialsBySubjectResponse);
  rpc CredentialsByIssuer  (QueryCredentialsByIssuerRequest)  returns (QueryCredentialsByIssuerResponse);
  rpc Anchor             (QueryAnchorRequest)             returns (QueryAnchorResponse);
  rpc AllAnchors         (QueryAllAnchorsRequest)         returns (QueryAllAnchorsResponse);
  rpc Params             (QueryParamsRequest)             returns (QueryParamsResponse);
}

message QueryDIDRequest  { string subject = 1; }
message QueryDIDResponse { DIDDocument document = 1 [(gogoproto.nullable) = false]; }

message QueryAllDIDsRequest  { cosmos.base.query.v1beta1.PageRequest pagination = 1; }
message QueryAllDIDsResponse {
  repeated DIDDocument documents = 1 [(gogoproto.nullable) = false];
  cosmos.base.query.v1beta1.PageResponse pagination = 2;
}

message QueryCredentialRequest  { string id = 1; }
message QueryCredentialResponse { CredentialStatus status = 1 [(gogoproto.nullable) = false]; }

message QueryCredentialsBySubjectRequest {
  string subject = 1;
  cosmos.base.query.v1beta1.PageRequest pagination = 2;
}
message QueryCredentialsBySubjectResponse {
  repeated CredentialStatus credentials = 1 [(gogoproto.nullable) = false];
  cosmos.base.query.v1beta1.PageResponse pagination = 2;
}

message QueryCredentialsByIssuerRequest {
  string issuer = 1;
  cosmos.base.query.v1beta1.PageRequest pagination = 2;
}
message QueryCredentialsByIssuerResponse {
  repeated CredentialStatus credentials = 1 [(gogoproto.nullable) = false];
  cosmos.base.query.v1beta1.PageResponse pagination = 2;
}

message QueryAnchorRequest  { string did = 1; }
message QueryAnchorResponse { TrustAnchor anchor = 1 [(gogoproto.nullable) = false]; }

message QueryAllAnchorsRequest  { cosmos.base.query.v1beta1.PageRequest pagination = 1; }
message QueryAllAnchorsResponse {
  repeated TrustAnchor anchors = 1 [(gogoproto.nullable) = false];
  cosmos.base.query.v1beta1.PageResponse pagination = 2;
}

message QueryParamsRequest  {}
message QueryParamsResponse { Params params = 1 [(gogoproto.nullable) = false]; }
