syntax = "proto3";
package energychain.cfe247.v1;

import "gogoproto/gogo.proto";
import "energychain/cfe247/v1/types.proto";

option go_package = "energychain/x/cfe247/types";

message RetirementAllocation {
  uint64 eac_retirement_id = 1;
  uint64 wh_allocated = 2;
}

message GenesisState {
  Params params = 1 [(gogoproto.nullable) = false];
  repeated DataProvider data_providers = 2 [(gogoproto.nullable) = false];
  repeated GridZone grid_zones = 3 [(gogoproto.nullable) = false];
  repeated Subject subjects = 4 [(gogoproto.nullable) = false];
  repeated HourlyConsumption consumptions = 5 [(gogoproto.nullable) = false];
  repeated MatchEntry matches = 6 [(gogoproto.nullable) = false];
  repeated HourlyAggregate aggregates = 7 [(gogoproto.nullable) = false];
  repeated AnnualScore annual_scores = 8 [(gogoproto.nullable) = false];
  repeated ReportPackage reports = 9 [(gogoproto.nullable) = false];
  repeated RetirementAllocation retirement_allocations = 10 [(gogoproto.nullable) = false];
  uint64 match_id_seq = 11;
  uint64 report_id_seq = 12;
}
