// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: energychain/stablecoin/v1/types.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// DenomStatus governs a registered stablecoin currency:
//
//	ACTIVE  — mints, burns, transfers all permitted.
//	PAUSED  — transfers + mints refused; burns + force operations
//	          still allowed so issuers can wind down a mis-issued
//	          denom or comply with a regulator's hold order.
//	RETIRED — no further state changes accepted; reserve linkage
//	          frozen. Used to permanently sunset a currency after
//	          every holder has redeemed.
type DenomStatus int32

const (
	DenomStatus_DENOM_STATUS_UNSPECIFIED DenomStatus = 0
	DenomStatus_DENOM_STATUS_ACTIVE      DenomStatus = 1
	DenomStatus_DENOM_STATUS_PAUSED      DenomStatus = 2
	DenomStatus_DENOM_STATUS_RETIRED     DenomStatus = 3
)

var DenomStatus_name = map[int32]string{
	0: "DENOM_STATUS_UNSPECIFIED",
	1: "DENOM_STATUS_ACTIVE",
	2: "DENOM_STATUS_PAUSED",
	3: "DENOM_STATUS_RETIRED",
}

var DenomStatus_value = map[string]int32{
	"DENOM_STATUS_UNSPECIFIED": 0,
	"DENOM_STATUS_ACTIVE":      1,
	"DENOM_STATUS_PAUSED":      2,
	"DENOM_STATUS_RETIRED":     3,
}

func (x DenomStatus) String() string {
	return proto.EnumName(DenomStatus_name, int32(x))
}

func (DenomStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f33dfee7960b088b, []int{0}
}

// IssuerStatus mirrors DenomStatus for the issuer entity:
//
//	ACTIVE   — may mint up to its quota and operate force operations
//	SUSPENDED — mint refused; force ops + burns still allowed (audit)
//	REVOKED  — issuer is dead; force ops also refused
type IssuerStatus int32

const (
	IssuerStatus_ISSUER_STATUS_UNSPECIFIED IssuerStatus = 0
	IssuerStatus_ISSUER_STATUS_ACTIVE      IssuerStatus = 1
	IssuerStatus_ISSUER_STATUS_SUSPENDED   IssuerStatus = 2
	IssuerStatus_ISSUER_STATUS_REVOKED     IssuerStatus = 3
)

var IssuerStatus_name = map[int32]string{
	0: "ISSUER_STATUS_UNSPECIFIED",
	1: "ISSUER_STATUS_ACTIVE",
	2: "ISSUER_STATUS_SUSPENDED",
	3: "ISSUER_STATUS_REVOKED",
}

var IssuerStatus_value = map[string]int32{
	"ISSUER_STATUS_UNSPECIFIED": 0,
	"ISSUER_STATUS_ACTIVE":      1,
	"ISSUER_STATUS_SUSPENDED":   2,
	"ISSUER_STATUS_REVOKED":     3,
}

func (x IssuerStatus) String() string {
	return proto.EnumName(IssuerStatus_name, int32(x))
}

func (IssuerStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f33dfee7960b088b, []int{1}
}

// RedemptionStatus tracks the off-chain settlement queue:
//
//	PENDING   — holder has burned tokens, awaiting fiat payout
//	FULFILLED — issuer recorded payout (with off-chain reference)
//	CANCELLED — holder withdrew or issuer rejected; tokens were
//	            re-minted to the holder when they cancelled
type RedemptionStatus int32

const (
	RedemptionStatus_REDEMPTION_STATUS_UNSPECIFIED RedemptionStatus = 0
	RedemptionStatus_REDEMPTION_STATUS_PENDING     RedemptionStatus = 1
	RedemptionStatus_REDEMPTION_STATUS_FULFILLED   RedemptionStatus = 2
	RedemptionStatus_REDEMPTION_STATUS_CANCELLED   RedemptionStatus = 3
)

var RedemptionStatus_name = map[int32]string{
	0: "REDEMPTION_STATUS_UNSPECIFIED",
	1: "REDEMPTION_STATUS_PENDING",
	2: "REDEMPTION_STATUS_FULFILLED",
	3: "REDEMPTION_STATUS_CANCELLED",
}

var RedemptionStatus_value = map[string]int32{
	"REDEMPTION_STATUS_UNSPECIFIED": 0,
	"REDEMPTION_STATUS_PENDING":     1,
	"REDEMPTION_STATUS_FULFILLED":   2,
	"REDEMPTION_STATUS_CANCELLED":   3,
}

func (x RedemptionStatus) String() string {
	return proto.EnumName(RedemptionStatus_name, int32(x))
}

func (RedemptionStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f33dfee7960b088b, []int{2}
}

// Denom is a registered stablecoin currency. Each denom has its own
// independent supply, issuer set, balance ledger, and reserve linkage
// — the spec calls this "各自独立合约空间" (separate contract spaces
// per currency).
type Denom struct {
	Id           string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Symbol       string      `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name         string      `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Decimals     uint32      `protobuf:"varint,4,opt,name=decimals,proto3" json:"decimals,omitempty"`
	Jurisdiction string      `protobuf:"bytes,5,opt,name=jurisdiction,proto3" json:"jurisdiction,omitempty"`
	Status       DenomStatus `protobuf:"varint,6,opt,name=status,proto3,enum=energychain.stablecoin.v1.DenomStatus" json:"status,omitempty"`
	// policy_id binds this denom to an x/policy DSL policy. Empty = no
	// policy (only baseline freeze + sanctions checks fire on transfer).
	PolicyId  string `protobuf:"bytes,7,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	CreatedBy string `protobuf:"bytes,8,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt int64  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt int64  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (m *Denom) Reset()         { *m = Denom{} }
func (m *Denom) String() string { return proto.CompactTextString(m) }
func (*Denom) ProtoMessage()    {}
func (*Denom) Descriptor() ([]byte, []int) {
	return fileDescriptor_f33dfee7960b088b, []int{0}
}
func (m *Denom) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Denom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Denom.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Denom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Denom.Merge(m, src)
}
func (m *Denom) XXX_Size() int {
	return m.Size()
}
func (m *Denom) XXX_DiscardUnknown() {
	xxx_messageInfo_Denom.DiscardUnknown(m)
}

var xxx_messageInfo_Denom proto.InternalMessageInfo

func (m *Denom) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Denom) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Denom) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Denom) GetDecimals() uint32 {
	if m != nil {
		return m.Decimals
	}
	return 0
}

func (m *Denom) GetJurisdiction() string {
	if m != nil {
		return m.Jurisdiction
	}
	return ""
}

func (m *Denom) GetStatus() DenomStatus {
	if m != nil {
		return m.Status
	}
	return DenomStatus_DENOM_STATUS_UNSPECIFIED
}

func (m *Denom) GetPolicyId() string {
	if m != nil {
		return m.PolicyId
	}
	return ""
}

func (m *Denom) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Denom) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Denom) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

// Issuer is a registered minting authority. The issuer is identified
// off-chain by its DID; on-chain, mint operations are authorised by
// addresses listed in `mint_authorities`.
//
// Multi-sig is achieved by wrapping the mint authority address in an
// upstream `x/auth` multisig account — the keeper checks AccessControl
// at single-address granularity.
type Issuer struct {
	Id          string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Did         string       `protobuf:"bytes,2,opt,name=did,proto3" json:"did,omitempty"`
	DisplayName string       `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Status      IssuerStatus `protobuf:"varint,4,opt,name=status,proto3,enum=energychain.stablecoin.v1.IssuerStatus" json:"status,omitempty"`
	// mint_authorities are the bech32 addresses that may sign MsgMint
	// for any denom under this issuer's quota. Up to a small bound
	// (Params.max_mint_authorities_per_issuer) so the linear contains
	// check stays cheap.
	MintAuthorities []string `protobuf:"bytes,5,rep,name=mint_authorities,json=mintAuthorities,proto3" json:"mint_authorities,omitempty"`
	// admin is the bech32 with permission to call freeze / blacklist /
	// force operations. Defaults to the registering authority.
	Admin     string `protobuf:"bytes,6,opt,name=admin,proto3" json:"admin,omitempty"`
	CreatedBy string `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt int64  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt int64  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (m *Issuer) Reset()         { *m = Issuer{} }
func (m *Issuer) String() string { return proto.CompactTextString(m) }
func (*Issuer) ProtoMessage()    {}
func (*Issuer) Descriptor() ([]byte, []int) {
	return fileDescriptor_f33dfee7960b088b, []int{1}
}
func (m *Issuer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Issuer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Issuer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Issuer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Issuer.Merge(m, src)
}
func (m *Issuer) XXX_Size() int {
	return m.Size()
}
func (m *Issuer) XXX_DiscardUnknown() {
	xxx_messageInfo_Issuer.DiscardUnknown(m)
}

var xxx_messageInfo_Issuer proto.InternalMessageInfo

func (m *Issuer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Issuer) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

func (m *Issuer) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Issuer) GetStatus() IssuerStatus {
	if m != nil {
		return m.Status
	}
	return IssuerStatus_ISSUER_STATUS_UNSPECIFIED
}

func (m *Issuer) GetMintAuthorities() []string {
	if m != nil {
		return m.MintAuthorities
	}
	return nil
}

func (m *Issuer) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

func (m *Issuer) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Issuer) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Issuer) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

// MintQuota caps how much an issuer may have outstanding for a given
// denom. Outstanding shrinks on burn / redemption; ceiling is set by
// governance.
type MintQuota struct {
	IssuerId    string `protobuf:"bytes,1,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	DenomId     string `protobuf:"bytes,2,opt,name=denom_id,json=denomId,proto3" json:"denom_id,omitempty"`
	Ceiling     uint64 `protobuf:"varint,3,opt,name=ceiling,proto3" json:"ceiling,omitempty"`
	Outstanding uint64 `protobuf:"varint,4,opt,name=outstanding,proto3" json:"outstanding,omitempty"`
	// mint_paused gives an issuer a circuit-breaker between governance
	// ceiling adjustments — they can pause their own minting without
	// touching the global denom or the on-chain quota.
	MintPaused bool  `protobuf:"varint,5,opt,name=mint_paused,json=mintPaused,proto3" json:"mint_paused,omitempty"`
	UpdatedAt  int64 `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (m *MintQuota) Reset()         { *m = MintQuota{} }
func (m *MintQuota) String() string { return proto.CompactTextString(m) }
func (*MintQuota) ProtoMessage()    {}
func (*MintQuota) Descriptor() ([]byte, []int) {
	return fileDescriptor_f33dfee7960b088b, []int{2}
}
func (m *MintQuota) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MintQuota) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MintQuota.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MintQuota) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MintQuota.Merge(m, src)
}
func (m *MintQuota) XXX_Size() int {
	return m.Size()
}
func (m *MintQuota) XXX_DiscardUnknown() {
	xxx_messageInfo_MintQuota.DiscardUnknown(m)
}

var xxx_messageInfo_MintQuota proto.InternalMessageInfo

func (m *MintQuota) GetIssuerId() string {
	if m != nil {
		return m.IssuerId
	}
	return ""
}

func (m *MintQuota) GetDenomId() string {
	if m != nil {
		return m.DenomId
	}
	return ""
}

func (m *MintQuota) GetCeiling() uint64 {
	if m != nil {
		return m.Ceiling
	}
	return 0
}

func (m *MintQuota) GetOutstanding() uint64 {
	if m != nil {
		return m.Outstanding
	}
	return 0
}

func (m *MintQuota) GetMintPaused() bool {
	if m != nil {
		return m.MintPaused
	}
	return false
}

func (m *MintQuota) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

// AccountFlags are per-(denom, account) compliance bits. An account
// flagged frozen cannot send or receive that denom; blacklisted is
// the harder variant that also bars redemption (used when an address
// is irrecoverably tainted).
type AccountFlags struct {
	DenomId         string `protobuf:"bytes,1,opt,name=denom_id,json=denomId,proto3" json:"denom_id,omitempty"`
	Account         string `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Frozen          bool   `protobuf:"varint,3,opt,name=frozen,proto3" json:"frozen,omitempty"`
	Blacklisted     bool   `protobuf:"varint,4,opt,name=blacklisted,proto3" json:"blacklisted,omitempty"`
	FreezeReason    string `protobuf:"bytes,5,opt,name=freeze_reason,json=freezeReason,proto3" json:"freeze_reason,omitempty"`
	BlacklistReason string `protobuf:"bytes,6,opt,name=blacklist_reason,json=blacklistReason,proto3" json:"blacklist_reason,omitempty"`
	FrozenAt        int64  `protobuf:"varint,7,opt,name=frozen_at,json=frozenAt,proto3" json:"frozen_at,omitempty"`
	BlacklistedAt   int64  `protobuf:"varint,8,opt,name=blacklisted_at,json=blacklistedAt,proto3" json:"blacklisted_at,omitempty"`
	UpdatedBy       string `protobuf:"bytes,9,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
}

func (m *AccountFlags) Reset()         { *m = AccountFlags{} }
func (m *AccountFlags) String() string { return proto.CompactTextString(m) }
func (*AccountFlags) ProtoMessage()    {}
func (*AccountFlags) Descriptor() ([]byte, []int) {
	return fileDescriptor_f33dfee7960b088b, []int{3}
}
func (m *AccountFlags) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccountFlags) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccountFlags.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccountFlags) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountFlags.Merge(m, src)
}
func (m *AccountFlags) XXX_Size() int {
	return m.Size()
}
func (m *AccountFlags) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountFlags.DiscardUnknown(m)
}

var xxx_messageInfo_AccountFlags proto.InternalMessageInfo

func (m *AccountFlags) GetDenomId() string {
	if m != nil {
		return m.DenomId
	}
	return ""
}

func (m *AccountFlags) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *AccountFlags) GetFrozen() bool {
	if m != nil {
		return m.Frozen
	}
	return false
}

func (m *AccountFlags) GetBlacklisted() bool {
	if m != nil {
		return m.Blacklisted
	}
	return false
}

func (m *AccountFlags) GetFreezeReason() string {
	if m != nil {
		return m.FreezeReason
	}
	return ""
}

func (m *AccountFlags) GetBlacklistReason() string {
	if m != nil {
		return m.BlacklistReason
	}
	return ""
}

func (m *AccountFlags) GetFrozenAt() int64 {
	if m != nil {
		return m.FrozenAt
	}
	return 0
}

func (m *AccountFlags) GetBlacklistedAt() int64 {
	if m != nil {
		return m.BlacklistedAt
	}
	return 0
}

func (m *AccountFlags) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

// DenomReserve binds a denom to an x/oracle reserve attestation
// topic. The keeper consults the topic on every mint to enforce the
// `outstanding * 10000 <= reserve_value * required_ratio_bps`
// invariant.
type DenomReserve struct {
	DenomId string `protobuf:"bytes,1,opt,name=denom_id,json=denomId,proto3" json:"denom_id,omitempty"`
	// oracle_topic_id resolves to an x/oracle Topic of kind RESERVE.
	// The aggregated value is consumed as the on-chain witness.
	OracleTopicId string `protobuf:"bytes,2,opt,name=oracle_topic_id,json=oracleTopicId,proto3" json:"oracle_topic_id,omitempty"`
	// required_ratio_bps is the minimum reserve coverage in basis
	// points (10_000 = 100%). 10_500 means 105% over-collateralised.
	RequiredRatioBps uint32 `protobuf:"varint,3,opt,name=required_ratio_bps,json=requiredRatioBps,proto3" json:"required_ratio_bps,omitempty"`
	// max_staleness_seconds bounds how old the latest aggregated value
	// may be before mints fail closed.
	MaxStalenessSeconds uint32 `protobuf:"varint,4,opt,name=max_staleness_seconds,json=maxStalenessSeconds,proto3" json:"max_staleness_seconds,omitempty"`
	UpdatedAt           int64  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (m *DenomReserve) Reset()         { *m = DenomReserve{} }
func (m *DenomReserve) String() string { return proto.CompactTextString(m) }
func (*DenomReserve) ProtoMessage()    {}
func (*DenomReserve) Descriptor() ([]byte, []int) {
	return fileDescriptor_f33dfee7960b088b, []int{4}
}
func (m *DenomReserve) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DenomReserve) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DenomReserve.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DenomReserve) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DenomReserve.Merge(m, src)
}
func (m *DenomReserve) XXX_Size() int {
	return m.Size()
}
func (m *DenomReserve) XXX_DiscardUnknown() {
	xxx_messageInfo_DenomReserve.DiscardUnknown(m)
}

var xxx_messageInfo_DenomReserve proto.InternalMessageInfo

func (m *DenomReserve) GetDenomId() string {
	if m != nil {
		return m.DenomId
	}
	return ""
}

func (m *DenomReserve) GetOracleTopicId() string {
	if m != nil {
		return m.OracleTopicId
	}
	return ""
}

func (m *DenomReserve) GetRequiredRatioBps() uint32 {
	if m != nil {
		return m.RequiredRatioBps
	}
	return 0
}

func (m *DenomReserve) GetMaxStalenessSeconds() uint32 {
	if m != nil {
		return m.MaxStalenessSeconds
	}
	return 0
}

func (m *DenomReserve) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

// Redemption is a single off-chain settlement request. Tokens are
// burned at request time so they cannot move while in queue; on
// fulfil the issuer records the off-chain payout reference; on
// cancel the tokens are re-minted to the holder.
type Redemption struct {
	Id       uint64           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DenomId  string           `protobuf:"bytes,2,opt,name=denom_id,json=denomId,proto3" json:"denom_id,omitempty"`
	Holder   string           `protobuf:"bytes,3,opt,name=holder,proto3" json:"holder,omitempty"`
	IssuerId string           `protobuf:"bytes,4,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	Amount   uint64           `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Status   RedemptionStatus `protobuf:"varint,6,opt,name=status,proto3,enum=energychain.stablecoin.v1.RedemptionStatus" json:"status,omitempty"`
	// payout_ref is the issuer's off-chain settlement reference (wire
	// tx hash, ACH trace, …). Filled in on Fulfill.
	PayoutRef    string `protobuf:"bytes,7,opt,name=payout_ref,json=payoutRef,proto3" json:"payout_ref,omitempty"`
	Memo         string `protobuf:"bytes,8,opt,name=memo,proto3" json:"memo,omitempty"`
	CancelReason string `protobuf:"bytes,9,opt,name=cancel_reason,json=cancelReason,proto3" json:"cancel_reason,omitempty"`
	RequestedAt  int64  `protobuf:"varint,10,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	ResolvedAt   int64  `protobuf:"varint,11,opt,name=resolved_at,json=resolvedAt,proto3" json:"resolved_at,omitempty"`
}

func (m *Redemption) Reset()         { *m = Redemption{} }
func (m *Redemption) String() string { return proto.CompactTextString(m) }
func (*Redemption) ProtoMessage()    {}
func (*Redemption) Descriptor() ([]byte, []int) {
	return fileDescriptor_f33dfee7960b088b, []int{5}
}
func (m *Redemption) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Redemption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Redemption.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Redemption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Redemption.Merge(m, src)
}
func (m *Redemption) XXX_Size() int {
	return m.Size()
}
func (m *Redemption) XXX_DiscardUnknown() {
	xxx_messageInfo_Redemption.DiscardUnknown(m)
}

var xxx_messageInfo_Redemption proto.InternalMessageInfo

func (m *Redemption) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Redemption) GetDenomId() string {
	if m != nil {
		return m.DenomId
	}
	return ""
}

func (m *Redemption) GetHolder() string {
	if m != nil {
		return m.Holder
	}
	return ""
}

func (m *Redemption) GetIssuerId() string {
	if m != nil {
		return m.IssuerId
	}
	return ""
}

func (m *Redemption) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Redemption) GetStatus() RedemptionStatus {
	if m != nil {
		return m.Status
	}
	return RedemptionStatus_REDEMPTION_STATUS_UNSPECIFIED
}

func (m *Redemption) GetPayoutRef() string {
	if m != nil {
		return m.PayoutRef
	}
	return ""
}

func (m *Redemption) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *Redemption) GetCancelReason() string {
	if m != nil {
		return m.CancelReason
	}
	return ""
}

func (m *Redemption) GetRequestedAt() int64 {
	if m != nil {
		return m.RequestedAt
	}
	return 0
}

func (m *Redemption) GetResolvedAt() int64 {
	if m != nil {
		return m.ResolvedAt
	}
	return 0
}

// Params governs the variable-length state collections.
type Params struct {
	MaxDenoms                      uint32 `protobuf:"varint,1,opt,name=max_denoms,json=maxDenoms,proto3" json:"max_denoms,omitempty"`
	MaxIssuers                     uint32 `protobuf:"varint,2,opt,name=max_issuers,json=maxIssuers,proto3" json:"max_issuers,omitempty"`
	MaxMintAuthoritiesPerIssuer    uint32 `protobuf:"varint,3,opt,name=max_mint_authorities_per_issuer,json=maxMintAuthoritiesPerIssuer,proto3" json:"max_mint_authorities_per_issuer,omitempty"`
	MaxRedemptionsPendingPerHolder uint32 `protobuf:"varint,4,opt,name=max_redemptions_pending_per_holder,json=maxRedemptionsPendingPerHolder,proto3" json:"max_redemptions_pending_per_holder,omitempty"`
	// mint_requires_reserve toggles the reserve-attestation gate. When
	// true, every MsgMint consults the oracle and refuses if the
	// attested reserve does not cover the post-mint outstanding at
	// required_ratio_bps. Default true; flip to false for testnets.
	MintRequiresReserve bool `protobuf:"varint,5,opt,name=mint_requires_reserve,json=mintRequiresReserve,proto3" json:"mint_requires_reserve,omitempty"`
	// require_kyc_credential, when non-empty, names a credential type
	// (e.g. "urn:vc:kyc:passed") every transfer counterparty MUST hold
	// — a defense-in-depth gate independent of x/policy.
	RequireKycCredential string `protobuf:"bytes,6,opt,name=require_kyc_credential,json=requireKycCredential,proto3" json:"require_kyc_credential,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_f33dfee7960b088b, []int{6}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMaxDenoms() uint32 {
	if m != nil {
		return m.MaxDenoms
	}
	return 0
}

func (m *Params) GetMaxIssuers() uint32 {
	if m != nil {
		return m.MaxIssuers
	}
	return 0
}

func (m *Params) GetMaxMintAuthoritiesPerIssuer() uint32 {
	if m != nil {
		return m.MaxMintAuthoritiesPerIssuer
	}
	return 0
}

func (m *Params) GetMaxRedemptionsPendingPerHolder() uint32 {
	if m != nil {
		return m.MaxRedemptionsPendingPerHolder
	}
	return 0
}

func (m *Params) GetMintRequiresReserve() bool {
	if m != nil {
		return m.MintRequiresReserve
	}
	return false
}

func (m *Params) GetRequireKycCredential() string {
	if m != nil {
		return m.RequireKycCredential
	}
	return ""
}

func init() {
	proto.RegisterEnum("energychain.stablecoin.v1.DenomStatus", DenomStatus_name, DenomStatus_value)
	proto.RegisterEnum("energychain.stablecoin.v1.IssuerStatus", IssuerStatus_name, IssuerStatus_value)
	proto.RegisterEnum("energychain.stablecoin.v1.RedemptionStatus", RedemptionStatus_name, RedemptionStatus_value)
	proto.RegisterType((*Denom)(nil), "energychain.stablecoin.v1.Denom")
	proto.RegisterType((*Issuer)(nil), "energychain.stablecoin.v1.Issuer")
	proto.RegisterType((*MintQuota)(nil), "energychain.stablecoin.v1.MintQuota")
	proto.RegisterType((*AccountFlags)(nil), "energychain.stablecoin.v1.AccountFlags")
	proto.RegisterType((*DenomReserve)(nil), "energychain.stablecoin.v1.DenomReserve")
	proto.RegisterType((*Redemption)(nil), "energychain.stablecoin.v1.Redemption")
	proto.RegisterType((*Params)(nil), "energychain.stablecoin.v1.Params")
}

func init() {
	proto.RegisterFile("energychain/stablecoin/v1/types.proto", fileDescriptor_f33dfee7960b088b)
}

var fileDescriptor_f33dfee7960b088b = []byte{
	// 1182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x56, 0x4f, 0x73, 0xdb, 0x44,
	0x14, 0x8f, 0xfc, 0x2f, 0xf6, 0xb3, 0xdd, 0x7a, 0xb6, 0x69, 0xaa, 0x34, 0xc4, 0x75, 0xcd, 0xb4,
	0x84, 0xc2, 0x24, 0xd3, 0xc2, 0x81, 0x13, 0x8c, 0x63, 0x2b, 0x20, 0xda, 0x38, 0x46, 0xb6, 0x7b,
	0xe0, 0xa2, 0x59, 0x4b, 0x9b, 0x64, 0xa9, 0xfe, 0xa1, 0x5d, 0x07, 0xab, 0x17, 0xbe, 0x02, 0x27,
	0x3e, 0x05, 0x07, 0xbe, 0x00, 0xc3, 0x85, 0x03, 0xc7, 0x0e, 0x27, 0x8e, 0x4c, 0x32, 0x7c, 0x0f,
	0x66, 0x57, 0xb2, 0x6c, 0x2b, 0xc1, 0x37, 0xbd, 0xdf, 0xef, 0xad, 0xde, 0xdb, 0xdf, 0xfb, 0x23,
	0xc1, 0x13, 0xe2, 0x91, 0xf0, 0x3c, 0xb2, 0x2e, 0x30, 0xf5, 0x0e, 0x19, 0xc7, 0x13, 0x87, 0x58,
	0x3e, 0xf5, 0x0e, 0x2f, 0x9f, 0x1f, 0xf2, 0x28, 0x20, 0xec, 0x20, 0x08, 0x7d, 0xee, 0xa3, 0x9d,
	0x25, 0xb7, 0x83, 0x85, 0xdb, 0xc1, 0xe5, 0xf3, 0x87, 0x5b, 0xe7, 0xfe, 0xb9, 0x2f, 0xbd, 0x0e,
	0xc5, 0x53, 0x7c, 0xa0, 0xfd, 0x5b, 0x0e, 0x8a, 0x3d, 0xe2, 0xf9, 0x2e, 0xba, 0x03, 0x39, 0x6a,
	0xab, 0x4a, 0x4b, 0xd9, 0xaf, 0x18, 0x39, 0x6a, 0xa3, 0x6d, 0x28, 0xb1, 0xc8, 0x9d, 0xf8, 0x8e,
	0x9a, 0x93, 0x58, 0x62, 0x21, 0x04, 0x05, 0x0f, 0xbb, 0x44, 0xcd, 0x4b, 0x54, 0x3e, 0xa3, 0x87,
	0x50, 0xb6, 0x89, 0x45, 0x5d, 0xec, 0x30, 0xb5, 0xd0, 0x52, 0xf6, 0xeb, 0x46, 0x6a, 0xa3, 0x36,
	0xd4, 0xbe, 0x9b, 0x86, 0x94, 0xd9, 0xd4, 0xe2, 0xd4, 0xf7, 0xd4, 0xa2, 0x3c, 0xb7, 0x82, 0xa1,
	0xcf, 0xa1, 0xc4, 0x38, 0xe6, 0x53, 0xa6, 0x96, 0x5a, 0xca, 0xfe, 0x9d, 0x17, 0x4f, 0x0f, 0xfe,
	0xf7, 0x1e, 0x07, 0x32, 0xdb, 0xa1, 0xf4, 0x36, 0x92, 0x53, 0x68, 0x17, 0x2a, 0x81, 0xef, 0x50,
	0x2b, 0x32, 0xa9, 0xad, 0x6e, 0xca, 0x00, 0xe5, 0x18, 0xd0, 0x6d, 0xb4, 0x07, 0x60, 0x85, 0x04,
	0x73, 0x62, 0x9b, 0x93, 0x48, 0x2d, 0x4b, 0xb6, 0x92, 0x20, 0x47, 0xd1, 0x32, 0x8d, 0xb9, 0x5a,
	0x69, 0x29, 0xfb, 0xf9, 0x94, 0xee, 0x70, 0x41, 0x4f, 0x03, 0x7b, 0x4e, 0x43, 0x4c, 0x27, 0x48,
	0x87, 0xb7, 0x7f, 0xc9, 0x41, 0x49, 0x67, 0x6c, 0x4a, 0xc2, 0x1b, 0x02, 0x36, 0x20, 0x6f, 0x53,
	0x3b, 0x51, 0x4f, 0x3c, 0xa2, 0xc7, 0x50, 0xb3, 0x29, 0x0b, 0x1c, 0x1c, 0x99, 0x4b, 0x12, 0x56,
	0x13, 0xac, 0x2f, 0x94, 0xfc, 0x22, 0x55, 0xa2, 0x20, 0x95, 0xf8, 0x60, 0x8d, 0x12, 0x71, 0xdc,
	0x8c, 0x14, 0x1f, 0x42, 0xc3, 0xa5, 0x1e, 0x37, 0xf1, 0x94, 0x5f, 0xf8, 0x21, 0xe5, 0x94, 0x30,
	0xb5, 0xd8, 0xca, 0xef, 0x57, 0x8c, 0xbb, 0x02, 0xef, 0x2c, 0x60, 0xb4, 0x05, 0x45, 0x6c, 0xbb,
	0xd4, 0x93, 0xa2, 0x57, 0x8c, 0xd8, 0xc8, 0xc8, 0xb5, 0xb9, 0x5e, 0xae, 0xf2, 0x7a, 0xb9, 0x2a,
	0x59, 0xb9, 0x7e, 0x57, 0xa0, 0x72, 0x42, 0x3d, 0xfe, 0xcd, 0xd4, 0xe7, 0x58, 0x94, 0x8d, 0xca,
	0x3b, 0x98, 0xa9, 0x70, 0xe5, 0x18, 0xd0, 0x6d, 0xb4, 0x23, 0x7a, 0xca, 0xf3, 0x5d, 0x33, 0xd5,
	0x70, 0x53, 0xda, 0xba, 0x8d, 0x54, 0xd8, 0xb4, 0x08, 0x75, 0xa8, 0x77, 0x2e, 0x25, 0x2c, 0x18,
	0x73, 0x13, 0xb5, 0xa0, 0xea, 0x4f, 0x39, 0xe3, 0xd8, 0xb3, 0x05, 0x5b, 0x90, 0xec, 0x32, 0x84,
	0x1e, 0x41, 0x55, 0xea, 0x13, 0xe0, 0x29, 0x23, 0xb6, 0xec, 0xc6, 0xb2, 0x01, 0x02, 0x1a, 0x48,
	0x24, 0x73, 0x83, 0x52, 0xf6, 0x06, 0xbf, 0xe6, 0xa0, 0xd6, 0xb1, 0x2c, 0x7f, 0xea, 0xf1, 0x63,
	0x07, 0x9f, 0xb3, 0x95, 0x3c, 0x95, 0x1b, 0x79, 0xe2, 0xd8, 0x75, 0x7e, 0x83, 0xc4, 0x14, 0xc3,
	0x75, 0x16, 0xfa, 0x6f, 0x89, 0x27, 0x2f, 0x50, 0x36, 0x12, 0x4b, 0xe4, 0x3f, 0x71, 0xb0, 0xf5,
	0xc6, 0xa1, 0x8c, 0x13, 0x5b, 0xe6, 0x5f, 0x36, 0x96, 0x21, 0xf4, 0x3e, 0xd4, 0xcf, 0x42, 0x42,
	0xde, 0x12, 0x33, 0x24, 0x98, 0x2d, 0xe6, 0x29, 0x06, 0x0d, 0x89, 0x89, 0x26, 0x48, 0xcf, 0xcc,
	0xfd, 0xe2, 0x22, 0xdf, 0x4d, 0xf1, 0xc4, 0x75, 0x17, 0x2a, 0x71, 0x6c, 0x71, 0xdb, 0x4d, 0x79,
	0xdb, 0x72, 0x0c, 0x74, 0x38, 0x7a, 0x02, 0x77, 0x96, 0x62, 0x2f, 0x0a, 0x5e, 0x5f, 0x42, 0x57,
	0x8b, 0x3e, 0x89, 0x64, 0xd1, 0x2b, 0xa9, 0x64, 0x47, 0x51, 0xfb, 0x2f, 0x05, 0x6a, 0x72, 0x6a,
	0x0d, 0xc2, 0x48, 0x78, 0x49, 0xd6, 0x49, 0xf6, 0x14, 0xee, 0xfa, 0x21, 0xb6, 0x1c, 0x62, 0x72,
	0x3f, 0xa0, 0xd6, 0xa2, 0xf8, 0xf5, 0x18, 0x1e, 0x09, 0x54, 0xb7, 0xd1, 0xc7, 0x80, 0x42, 0xf2,
	0xfd, 0x94, 0x86, 0xc4, 0x36, 0x43, 0xcc, 0xa9, 0x6f, 0x4e, 0x02, 0x26, 0xc5, 0xac, 0x1b, 0x8d,
	0x39, 0x63, 0x08, 0xe2, 0x28, 0x60, 0xe8, 0x05, 0xdc, 0x77, 0xf1, 0xcc, 0x64, 0x1c, 0x3b, 0xc4,
	0x23, 0x8c, 0x99, 0x8c, 0x58, 0xbe, 0x67, 0xcf, 0x97, 0xd5, 0x3d, 0x17, 0xcf, 0x86, 0x73, 0x6e,
	0x18, 0x53, 0x99, 0x3e, 0x28, 0x66, 0xfb, 0xe0, 0xdf, 0x1c, 0x80, 0x41, 0x6c, 0xe2, 0x06, 0x72,
	0x83, 0x2d, 0x86, 0xbf, 0x20, 0x87, 0x7f, 0x4d, 0xf7, 0x6e, 0x43, 0xe9, 0xc2, 0x77, 0x6c, 0x12,
	0x26, 0xf3, 0x9f, 0x58, 0xab, 0xd3, 0x50, 0xc8, 0x4c, 0xc3, 0x36, 0x94, 0xb0, 0x2b, 0x3b, 0xa9,
	0x28, 0x63, 0x24, 0x16, 0xea, 0x66, 0x36, 0xe7, 0x47, 0x6b, 0xf6, 0xc5, 0x22, 0xdd, 0xcc, 0xce,
	0xd8, 0x03, 0x08, 0x70, 0xe4, 0x4f, 0x45, 0xaf, 0x9c, 0xcd, 0x47, 0x3e, 0x46, 0x0c, 0x72, 0x26,
	0x36, 0xbe, 0x4b, 0x5c, 0x3f, 0x59, 0x9d, 0xf2, 0x59, 0xb4, 0xa1, 0x85, 0x3d, 0x8b, 0x38, 0xf3,
	0xf6, 0x8a, 0xab, 0x5e, 0x8b, 0xc1, 0xa4, 0xb7, 0x1e, 0x43, 0x4d, 0x94, 0x82, 0xb0, 0x95, 0xed,
	0x59, 0x4d, 0xb1, 0x0e, 0x17, 0xe3, 0x18, 0x12, 0xe6, 0x3b, 0x97, 0xb1, 0x47, 0x55, 0x7a, 0xc0,
	0x1c, 0xea, 0xf0, 0xf6, 0x1f, 0x39, 0x28, 0x0d, 0x70, 0x88, 0x5d, 0x99, 0xa6, 0xa8, 0xa2, 0xd4,
	0x91, 0x49, 0xad, 0xeb, 0x46, 0xc5, 0xc5, 0x33, 0xd9, 0x5b, 0x4c, 0x4e, 0x36, 0x9e, 0x99, 0xb1,
	0x64, 0x4c, 0xaa, 0x5e, 0x37, 0xc4, 0x89, 0x78, 0x4f, 0x32, 0xd4, 0x83, 0x47, 0xc2, 0x21, 0xbb,
	0x1e, 0xcd, 0x40, 0x48, 0x2e, 0x7d, 0x92, 0x06, 0xda, 0x75, 0xf1, 0xec, 0x64, 0x75, 0x59, 0x0e,
	0x48, 0x98, 0xac, 0xf9, 0xaf, 0xa1, 0x2d, 0xde, 0x12, 0xa6, 0x62, 0x8a, 0x17, 0xc8, 0xdd, 0x22,
	0x5f, 0x94, 0x94, 0x36, 0x6e, 0xac, 0xa6, 0x8b, 0x67, 0x0b, 0xd5, 0xd9, 0x20, 0xf6, 0x1b, 0x90,
	0xf0, 0xab, 0xb8, 0xe4, 0xa2, 0x2f, 0x45, 0x36, 0x49, 0xc3, 0x32, 0x33, 0x8c, 0x27, 0x24, 0x59,
	0x4b, 0xf7, 0x04, 0x69, 0x24, 0xdc, 0x7c, 0x78, 0x3e, 0x85, 0xed, 0xc4, 0xdd, 0x7c, 0x13, 0x59,
	0xa6, 0x25, 0x12, 0xf1, 0x38, 0xc5, 0x4e, 0x32, 0xe1, 0x5b, 0x09, 0xfb, 0x32, 0xb2, 0xba, 0x29,
	0xf7, 0xec, 0x07, 0xa8, 0x2e, 0x7d, 0x38, 0xd1, 0x7b, 0xa0, 0xf6, 0xb4, 0xfe, 0xe9, 0x89, 0x39,
	0x1c, 0x75, 0x46, 0xe3, 0xa1, 0x39, 0xee, 0x0f, 0x07, 0x5a, 0x57, 0x3f, 0xd6, 0xb5, 0x5e, 0x63,
	0x03, 0x3d, 0x80, 0x7b, 0x2b, 0x6c, 0xa7, 0x3b, 0xd2, 0x5f, 0x6b, 0x0d, 0xe5, 0x06, 0x31, 0xe8,
	0x8c, 0x87, 0x5a, 0xaf, 0x91, 0x43, 0x2a, 0x6c, 0xad, 0x10, 0x86, 0x36, 0xd2, 0x0d, 0xad, 0xd7,
	0xc8, 0x3f, 0xfb, 0x11, 0x6a, 0xcb, 0xdf, 0x29, 0xb4, 0x07, 0x3b, 0xfa, 0x70, 0x38, 0xd6, 0x8c,
	0xdb, 0x43, 0xab, 0xb0, 0xb5, 0x4a, 0xa7, 0xb1, 0x77, 0xe1, 0xc1, 0x2a, 0x33, 0x1c, 0x0f, 0x07,
	0x5a, 0xbf, 0x27, 0xe3, 0xef, 0xc0, 0xfd, 0x55, 0xd2, 0xd0, 0x5e, 0x9f, 0xbe, 0x94, 0x09, 0xfc,
	0xac, 0x40, 0x23, 0xdb, 0xf9, 0xe8, 0x31, 0xec, 0x19, 0x5a, 0x4f, 0x3b, 0x19, 0x8c, 0xf4, 0xd3,
	0xfe, 0xed, 0x99, 0xec, 0xc1, 0xce, 0x4d, 0x17, 0x11, 0x50, 0xef, 0x7f, 0xd9, 0x50, 0xd0, 0x23,
	0xd8, 0xbd, 0x49, 0x1f, 0x8f, 0x5f, 0x1d, 0xeb, 0xaf, 0x5e, 0xc9, 0x94, 0x6e, 0x75, 0xe8, 0x76,
	0xfa, 0x5d, 0x4d, 0x3a, 0xe4, 0x8f, 0x3e, 0xfb, 0xf3, 0xaa, 0xa9, 0xbc, 0xbb, 0x6a, 0x2a, 0xff,
	0x5c, 0x35, 0x95, 0x9f, 0xae, 0x9b, 0x1b, 0xef, 0xae, 0x9b, 0x1b, 0x7f, 0x5f, 0x37, 0x37, 0xbe,
	0x6d, 0x2e, 0xff, 0xec, 0xcd, 0x96, 0x7f, 0xf7, 0xe4, 0xbf, 0xde, 0xa4, 0x24, 0xff, 0xdd, 0x3e,
	0xf9, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x3b, 0x9a, 0x3d, 0x8c, 0x15, 0x0a, 0x00, 0x00,
}

func (m *Denom) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Denom) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Denom) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UpdatedAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.UpdatedAt))
		i--
		dAtA[i] = 0x50
	}
	if m.CreatedAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x48
	}
	if len(m.CreatedBy) > 0 {
		i -= len(m.CreatedBy)
		copy(dAtA[i:], m.CreatedBy)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.CreatedBy)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.PolicyId) > 0 {
		i -= len(m.PolicyId)
		copy(dAtA[i:], m.PolicyId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.PolicyId)))
		i--
		dAtA[i] = 0x3a
	}
	if m.Status != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Jurisdiction) > 0 {
		i -= len(m.Jurisdiction)
		copy(dAtA[i:], m.Jurisdiction)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Jurisdiction)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Decimals != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Decimals))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Symbol) > 0 {
		i -= len(m.Symbol)
		copy(dAtA[i:], m.Symbol)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Symbol)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Issuer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Issuer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Issuer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UpdatedAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.UpdatedAt))
		i--
		dAtA[i] = 0x48
	}
	if m.CreatedAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x40
	}
	if len(m.CreatedBy) > 0 {
		i -= len(m.CreatedBy)
		copy(dAtA[i:], m.CreatedBy)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.CreatedBy)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Admin) > 0 {
		i -= len(m.Admin)
		copy(dAtA[i:], m.Admin)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Admin)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.MintAuthorities) > 0 {
		for iNdEx := len(m.MintAuthorities) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.MintAuthorities[iNdEx])
			copy(dAtA[i:], m.MintAuthorities[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.MintAuthorities[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.Status != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x20
	}
	if len(m.DisplayName) > 0 {
		i -= len(m.DisplayName)
		copy(dAtA[i:], m.DisplayName)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.DisplayName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Did) > 0 {
		i -= len(m.Did)
		copy(dAtA[i:], m.Did)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Did)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MintQuota) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MintQuota) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MintQuota) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UpdatedAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.UpdatedAt))
		i--
		dAtA[i] = 0x30
	}
	if m.MintPaused {
		i--
		if m.MintPaused {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.Outstanding != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Outstanding))
		i--
		dAtA[i] = 0x20
	}
	if m.Ceiling != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Ceiling))
		i--
		dAtA[i] = 0x18
	}
	if len(m.DenomId) > 0 {
		i -= len(m.DenomId)
		copy(dAtA[i:], m.DenomId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.DenomId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.IssuerId) > 0 {
		i -= len(m.IssuerId)
		copy(dAtA[i:], m.IssuerId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.IssuerId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AccountFlags) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccountFlags) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AccountFlags) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UpdatedBy) > 0 {
		i -= len(m.UpdatedBy)
		copy(dAtA[i:], m.UpdatedBy)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.UpdatedBy)))
		i--
		dAtA[i] = 0x4a
	}
	if m.BlacklistedAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.BlacklistedAt))
		i--
		dAtA[i] = 0x40
	}
	if m.FrozenAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.FrozenAt))
		i--
		dAtA[i] = 0x38
	}
	if len(m.BlacklistReason) > 0 {
		i -= len(m.BlacklistReason)
		copy(dAtA[i:], m.BlacklistReason)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.BlacklistReason)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.FreezeReason) > 0 {
		i -= len(m.FreezeReason)
		copy(dAtA[i:], m.FreezeReason)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.FreezeReason)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Blacklisted {
		i--
		if m.Blacklisted {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.Frozen {
		i--
		if m.Frozen {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.Account) > 0 {
		i -= len(m.Account)
		copy(dAtA[i:], m.Account)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Account)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.DenomId) > 0 {
		i -= len(m.DenomId)
		copy(dAtA[i:], m.DenomId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.DenomId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DenomReserve) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DenomReserve) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DenomReserve) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UpdatedAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.UpdatedAt))
		i--
		dAtA[i] = 0x28
	}
	if m.MaxStalenessSeconds != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MaxStalenessSeconds))
		i--
		dAtA[i] = 0x20
	}
	if m.RequiredRatioBps != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.RequiredRatioBps))
		i--
		dAtA[i] = 0x18
	}
	if len(m.OracleTopicId) > 0 {
		i -= len(m.OracleTopicId)
		copy(dAtA[i:], m.OracleTopicId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.OracleTopicId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.DenomId) > 0 {
		i -= len(m.DenomId)
		copy(dAtA[i:], m.DenomId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.DenomId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Redemption) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Redemption) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Redemption) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ResolvedAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ResolvedAt))
		i--
		dAtA[i] = 0x58
	}
	if m.RequestedAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.RequestedAt))
		i--
		dAtA[i] = 0x50
	}
	if len(m.CancelReason) > 0 {
		i -= len(m.CancelReason)
		copy(dAtA[i:], m.CancelReason)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.CancelReason)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Memo) > 0 {
		i -= len(m.Memo)
		copy(dAtA[i:], m.Memo)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Memo)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.PayoutRef) > 0 {
		i -= len(m.PayoutRef)
		copy(dAtA[i:], m.PayoutRef)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.PayoutRef)))
		i--
		dAtA[i] = 0x3a
	}
	if m.Status != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x30
	}
	if m.Amount != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.IssuerId) > 0 {
		i -= len(m.IssuerId)
		copy(dAtA[i:], m.IssuerId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.IssuerId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Holder) > 0 {
		i -= len(m.Holder)
		copy(dAtA[i:], m.Holder)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Holder)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.DenomId) > 0 {
		i -= len(m.DenomId)
		copy(dAtA[i:], m.DenomId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.DenomId)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RequireKycCredential) > 0 {
		i -= len(m.RequireKycCredential)
		copy(dAtA[i:], m.RequireKycCredential)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.RequireKycCredential)))
		i--
		dAtA[i] = 0x32
	}
	if m.MintRequiresReserve {
		i--
		if m.MintRequiresReserve {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.MaxRedemptionsPendingPerHolder != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MaxRedemptionsPendingPerHolder))
		i--
		dAtA[i] = 0x20
	}
	if m.MaxMintAuthoritiesPerIssuer != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MaxMintAuthoritiesPerIssuer))
		i--
		dAtA[i] = 0x18
	}
	if m.MaxIssuers != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MaxIssuers))
		i--
		dAtA[i] = 0x10
	}
	if m.MaxDenoms != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MaxDenoms))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Denom) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Symbol)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Decimals != 0 {
		n += 1 + sovTypes(uint64(m.Decimals))
	}
	l = len(m.Jurisdiction)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovTypes(uint64(m.Status))
	}
	l = len(m.PolicyId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.CreatedBy)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovTypes(uint64(m.CreatedAt))
	}
	if m.UpdatedAt != 0 {
		n += 1 + sovTypes(uint64(m.UpdatedAt))
	}
	return n
}

func (m *Issuer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Did)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.DisplayName)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovTypes(uint64(m.Status))
	}
	if len(m.MintAuthorities) > 0 {
		for _, s := range m.MintAuthorities {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	l = len(m.Admin)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.CreatedBy)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovTypes(uint64(m.CreatedAt))
	}
	if m.UpdatedAt != 0 {
		n += 1 + sovTypes(uint64(m.UpdatedAt))
	}
	return n
}

func (m *MintQuota) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.IssuerId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.DenomId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Ceiling != 0 {
		n += 1 + sovTypes(uint64(m.Ceiling))
	}
	if m.Outstanding != 0 {
		n += 1 + sovTypes(uint64(m.Outstanding))
	}
	if m.MintPaused {
		n += 2
	}
	if m.UpdatedAt != 0 {
		n += 1 + sovTypes(uint64(m.UpdatedAt))
	}
	return n
}

func (m *AccountFlags) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DenomId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Frozen {
		n += 2
	}
	if m.Blacklisted {
		n += 2
	}
	l = len(m.FreezeReason)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.BlacklistReason)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.FrozenAt != 0 {
		n += 1 + sovTypes(uint64(m.FrozenAt))
	}
	if m.BlacklistedAt != 0 {
		n += 1 + sovTypes(uint64(m.BlacklistedAt))
	}
	l = len(m.UpdatedBy)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *DenomReserve) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DenomId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.OracleTopicId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.RequiredRatioBps != 0 {
		n += 1 + sovTypes(uint64(m.RequiredRatioBps))
	}
	if m.MaxStalenessSeconds != 0 {
		n += 1 + sovTypes(uint64(m.MaxStalenessSeconds))
	}
	if m.UpdatedAt != 0 {
		n += 1 + sovTypes(uint64(m.UpdatedAt))
	}
	return n
}

func (m *Redemption) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTypes(uint64(m.Id))
	}
	l = len(m.DenomId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Holder)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.IssuerId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovTypes(uint64(m.Amount))
	}
	if m.Status != 0 {
		n += 1 + sovTypes(uint64(m.Status))
	}
	l = len(m.PayoutRef)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Memo)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.CancelReason)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.RequestedAt != 0 {
		n += 1 + sovTypes(uint64(m.RequestedAt))
	}
	if m.ResolvedAt != 0 {
		n += 1 + sovTypes(uint64(m.ResolvedAt))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxDenoms != 0 {
		n += 1 + sovTypes(uint64(m.MaxDenoms))
	}
	if m.MaxIssuers != 0 {
		n += 1 + sovTypes(uint64(m.MaxIssuers))
	}
	if m.MaxMintAuthoritiesPerIssuer != 0 {
		n += 1 + sovTypes(uint64(m.MaxMintAuthoritiesPerIssuer))
	}
	if m.MaxRedemptionsPendingPerHolder != 0 {
		n += 1 + sovTypes(uint64(m.MaxRedemptionsPendingPerHolder))
	}
	if m.MintRequiresReserve {
		n += 2
	}
	l = len(m.RequireKycCredential)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Denom) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Denom: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Denom: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Symbol", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Symbol = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Decimals", wireType)
			}
			m.Decimals = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Decimals |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Jurisdiction", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Jurisdiction = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= DenomStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PolicyId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			m.UpdatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Issuer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Issuer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Issuer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Did = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisplayName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DisplayName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= IssuerStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintAuthorities", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MintAuthorities = append(m.MintAuthorities, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			m.UpdatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MintQuota) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MintQuota: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MintQuota: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IssuerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DenomId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DenomId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ceiling", wireType)
			}
			m.Ceiling = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Ceiling |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Outstanding", wireType)
			}
			m.Outstanding = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Outstanding |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintPaused", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MintPaused = bool(v != 0)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			m.UpdatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AccountFlags) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccountFlags: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccountFlags: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DenomId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DenomId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Frozen", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Frozen = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Blacklisted", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Blacklisted = bool(v != 0)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FreezeReason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FreezeReason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlacklistReason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlacklistReason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FrozenAt", wireType)
			}
			m.FrozenAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FrozenAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlacklistedAt", wireType)
			}
			m.BlacklistedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlacklistedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UpdatedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DenomReserve) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DenomReserve: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DenomReserve: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DenomId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DenomId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleTopicId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OracleTopicId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequiredRatioBps", wireType)
			}
			m.RequiredRatioBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequiredRatioBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxStalenessSeconds", wireType)
			}
			m.MaxStalenessSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxStalenessSeconds |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			m.UpdatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Redemption) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Redemption: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Redemption: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DenomId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DenomId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Holder", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Holder = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IssuerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= RedemptionStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PayoutRef", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PayoutRef = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Memo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CancelReason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CancelReason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestedAt", wireType)
			}
			m.RequestedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResolvedAt", wireType)
			}
			m.ResolvedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ResolvedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxDenoms", wireType)
			}
			m.MaxDenoms = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxDenoms |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxIssuers", wireType)
			}
			m.MaxIssuers = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxIssuers |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxMintAuthoritiesPerIssuer", wireType)
			}
			m.MaxMintAuthoritiesPerIssuer = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxMintAuthoritiesPerIssuer |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxRedemptionsPendingPerHolder", wireType)
			}
			m.MaxRedemptionsPendingPerHolder = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxRedemptionsPendingPerHolder |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintRequiresReserve", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MintRequiresReserve = bool(v != 0)
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequireKycCredential", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequireKycCredential = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
