syntax = "proto3";
package energychain.market.v1;

import "cosmos/base/query/v1beta1/pagination.proto";
import "gogoproto/gogo.proto";

import "energychain/market/v1/types.proto";

option go_package = "energychain/x/market/types";

service Query {
  rpc Params(QueryParamsRequest) returns (QueryParamsResponse);
  rpc Pair(QueryPairRequest) returns (QueryPairResponse);
  rpc Pairs(QueryPairsRequest) returns (QueryPairsResponse);
  rpc Order(QueryOrderRequest) returns (QueryOrderResponse);
  rpc OpenOrders(QueryOpenOrdersRequest) returns (QueryOpenOrdersResponse);
  rpc OrdersByOwner(QueryOrdersByOwnerRequest) returns (QueryOrdersByOwnerResponse);
  rpc Position(QueryPositionRequest) returns (QueryPositionResponse);
  rpc PoolAddress(QueryPoolAddressRequest) returns (QueryPoolAddressResponse);
}

message QueryParamsRequest {}
message QueryParamsResponse { Params params = 1 [(gogoproto.nullable) = false]; }

message QueryPairRequest { uint64 id = 1; }
message QueryPairResponse { Pair pair = 1 [(gogoproto.nullable) = false]; }

message QueryPairsRequest { cosmos.base.query.v1beta1.PageRequest pagination = 1; }
message QueryPairsResponse {
  repeated Pair pairs = 1 [(gogoproto.nullable) = false];
  cosmos.base.query.v1beta1.PageResponse pagination = 2;
}

message QueryOrderRequest { uint64 id = 1; }
message QueryOrderResponse { Order order = 1 [(gogoproto.nullable) = false]; }

message QueryOpenOrdersRequest {
  uint64 pair_id = 1;
  Side side = 2; // 0=any
  cosmos.base.query.v1beta1.PageRequest pagination = 3;
}
message QueryOpenOrdersResponse {
  repeated Order orders = 1 [(gogoproto.nullable) = false];
  cosmos.base.query.v1beta1.PageResponse pagination = 2;
}

message QueryOrdersByOwnerRequest {
  string owner = 1;
  cosmos.base.query.v1beta1.PageRequest pagination = 2;
}
message QueryOrdersByOwnerResponse {
  repeated Order orders = 1 [(gogoproto.nullable) = false];
  cosmos.base.query.v1beta1.PageResponse pagination = 2;
}

message QueryPositionRequest {
  uint64 pair_id = 1;
  string owner = 2;
}
message QueryPositionResponse { Position position = 1 [(gogoproto.nullable) = false]; }

message QueryPoolAddressRequest {}
message QueryPoolAddressResponse { string pool = 1; }
