syntax = "proto3";
package energychain.energy.v1;

import "gogoproto/gogo.proto";
import "cosmos/base/query/v1beta1/pagination.proto";
import "energychain/energy/v1/types.proto";

option go_package = "energychain/x/energy/types";

// Query defines the energy module gRPC query service.
service Query {
  rpc EnergyData(QueryEnergyDataRequest) returns (QueryEnergyDataResponse);
  rpc EnergyDataByCategory(QueryEnergyDataByCategoryRequest) returns (QueryEnergyDataByCategoryResponse);
  rpc EnergyDataBySubmitter(QueryEnergyDataBySubmitterRequest) returns (QueryEnergyDataBySubmitterResponse);
  rpc Batch(QueryBatchRequest) returns (QueryBatchResponse);
  rpc Params(QueryParamsRequest) returns (QueryParamsResponse);
}

message QueryEnergyDataRequest { string id = 1 [(gogoproto.customname) = "ID"]; }
message QueryEnergyDataResponse { EnergyData data = 1 [(gogoproto.nullable) = false]; }

message QueryEnergyDataByCategoryRequest {
  string category = 1;
  cosmos.base.query.v1beta1.PageRequest pagination = 2;
}
message QueryEnergyDataByCategoryResponse {
  repeated EnergyData data = 1 [(gogoproto.nullable) = false];
  cosmos.base.query.v1beta1.PageResponse pagination = 2;
}

message QueryEnergyDataBySubmitterRequest {
  string submitter = 1;
  cosmos.base.query.v1beta1.PageRequest pagination = 2;
}
message QueryEnergyDataBySubmitterResponse {
  repeated EnergyData data = 1 [(gogoproto.nullable) = false];
  cosmos.base.query.v1beta1.PageResponse pagination = 2;
}

message QueryBatchRequest { string id = 1 [(gogoproto.customname) = "ID"]; }
message QueryBatchResponse { BatchSubmission batch = 1 [(gogoproto.nullable) = false]; }

message QueryParamsRequest {}
message QueryParamsResponse { Params params = 1 [(gogoproto.nullable) = false]; }
